package authentication

// This file is auto-generated, don't edit it. Thanks.
import (
  "github.com/alibabacloud-go/tea/tea"
)

type CreateUserRequest struct {
  // {"en":"username
  // 
  // Format: 2-32 characters, can contain Chinese, English, numbers and symbols @ . _ -
  // 
  // This parameter must be specified.", "zh_CN":"用户名
  // 2-32个字符，支持中文、英文、数字和符号@._-
  // 该参数必须指定"}
  Username *string `json:"username,omitempty" xml:"username,omitempty" require:"true"`
  // {"en":"Whether to send the password to the user mobile, the default is 0
  // 0: Do not send
  // 1: send", "zh_CN":"是否发送密码给用户的手机，默认0
  // 0：不发送
  // 1：发送"}
  PhoneSendPwd *int `json:"phoneSendPwd,omitempty" xml:"phoneSendPwd,omitempty"`
  // {"en":"Whether to send the password to the user&lsquo;s email, the default is 0
  // 0: Do not send
  // 1: send", "zh_CN":"是否发送密码给用户的邮箱，默认0
  // 0：不发送
  // 1：发送"}
  EmailSendPwd *int `json:"emailSendPwd,omitempty" xml:"emailSendPwd,omitempty"`
  // {"en":"If the parameter is  \"\" or null, it will be randomly generated by system.
  // If the parameter is not empty, it will be the password for user.
  // Format: 8-32 characters, including at least 3 types of uppercase letters, lowercase letters, numbers and punctuation marks", "zh_CN":"若传参为空或不传,则随机生成
  // 若传参不为空，则为预设密码
  // 8-32个字符，字母大写、字母小写、数字和标点符号至少包含3种"}
  Password *string `json:"password,omitempty" xml:"password,omitempty"`
  // {"en":"Parent group name.
  // If the request parameters do not contain this field or it is empty, the user will belongs the root deirectory group.", "zh_CN":"父组名称
  // 不传或空保存在根用户组下"}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty"`
  // {"en":"Bandwidth limit.
  // If the parameters do not contains this field,it  will be 1/2 of maximum bandwidth limit.
  // If the value exceeds the maximum bandwidth,it  will be maximum bandwidth limit.", "zh_CN":"带宽限制
  // 不传参为 1/2{最大带宽}
  // 传参超过最大带宽，则为{最大带宽}"}
  Bandwidth *float64 `json:"bandwidth,omitempty" xml:"bandwidth,omitempty"`
  // {"en":"Area code
  // If the areaCode is null and when cellPhone is not null, areaCode  will be 86.", "zh_CN":"区号，手机号存在但区号不存在时会默认设置86"}
  AreaCode *string `json:"areaCode,omitempty" xml:"areaCode,omitempty"`
  // {"en":"Mobile.When phoneSendPwd is equal to \"1\", this field cannnot be empty.", "zh_CN":"手机号；当phoneSendPwd=1时，不为空"}
  CellPhone *string `json:"cellPhone,omitempty" xml:"cellPhone,omitempty"`
  // {"en":"Email.
  // When emailSendPwd is equal to \"1\", this field cannnot be empty.", "zh_CN":"邮箱
  // 当emailSendPwd=1时，不为空"}
  Email *string `json:"email,omitempty" xml:"email,omitempty"`
  // {"en":"MFA: message authentication, default 0
  // \"0\": off,
  // \"1\":  on", "zh_CN":"双因子认证 : 短信认证，默认0
  // 0 关闭， 1 开启"}
  SmsAuth *int `json:"smsAuth,omitempty" xml:"smsAuth,omitempty"`
  // {"en":"MFA: totp authentication, default 0
  // \"0\": off,
  // \"1\":  on", "zh_CN":"双因子认证 : totp认证，默认0
  // 0 关闭， 1 开启"}
  TotpAuth *int `json:"totpAuth,omitempty" xml:"totpAuth,omitempty"`
  // {"en":"Expiration time: pass timestamp, millisecond level
  // If the parameters do not contain the filed, it will be \"0\"
  // 0: never expire
  // 1626732871372: Set expiration time", "zh_CN":"过期时间，传时间戳，毫秒级别，不传为0
  // 0：永不过期
  // 1626732871372：设置过期时间"}
  ExpireTime *int64 `json:"expireTime,omitempty" xml:"expireTime,omitempty"`
  // {"en":"Whether to enable the user, do not pass the parameter to enable
  // 1: enable
  // 0: disable", "zh_CN":"是否启用用户，不传参为启用
  // 1:启用
  // 0:禁用"}
  EnableStatus *int `json:"enableStatus,omitempty" xml:"enableStatus,omitempty"`
  // {"en":"Note
  // Maximum length is 255 characters.", "zh_CN":"备注
  // 最大长度255个字符"}
  Remark *string `json:"remark,omitempty" xml:"remark,omitempty"`
}

func (s CreateUserRequest) String() string {
  return tea.Prettify(s)
}

func (s CreateUserRequest) GoString() string {
  return s.String()
}

func (s *CreateUserRequest) SetUsername(v string) *CreateUserRequest {
  s.Username = &v
  return s
}

func (s *CreateUserRequest) SetPhoneSendPwd(v int) *CreateUserRequest {
  s.PhoneSendPwd = &v
  return s
}

func (s *CreateUserRequest) SetEmailSendPwd(v int) *CreateUserRequest {
  s.EmailSendPwd = &v
  return s
}

func (s *CreateUserRequest) SetPassword(v string) *CreateUserRequest {
  s.Password = &v
  return s
}

func (s *CreateUserRequest) SetGroupName(v string) *CreateUserRequest {
  s.GroupName = &v
  return s
}

func (s *CreateUserRequest) SetBandwidth(v float64) *CreateUserRequest {
  s.Bandwidth = &v
  return s
}

func (s *CreateUserRequest) SetAreaCode(v string) *CreateUserRequest {
  s.AreaCode = &v
  return s
}

func (s *CreateUserRequest) SetCellPhone(v string) *CreateUserRequest {
  s.CellPhone = &v
  return s
}

func (s *CreateUserRequest) SetEmail(v string) *CreateUserRequest {
  s.Email = &v
  return s
}

func (s *CreateUserRequest) SetSmsAuth(v int) *CreateUserRequest {
  s.SmsAuth = &v
  return s
}

func (s *CreateUserRequest) SetTotpAuth(v int) *CreateUserRequest {
  s.TotpAuth = &v
  return s
}

func (s *CreateUserRequest) SetExpireTime(v int64) *CreateUserRequest {
  s.ExpireTime = &v
  return s
}

func (s *CreateUserRequest) SetEnableStatus(v int) *CreateUserRequest {
  s.EnableStatus = &v
  return s
}

func (s *CreateUserRequest) SetRemark(v string) *CreateUserRequest {
  s.Remark = &v
  return s
}

type CreateUserResponse struct {
  // {'en':'Interface error code, 0-fail,1-success', 'zh_CN':'接口错误码，0-代表失败，1-代表成功'}
  ReturnCode *string `json:"returnCode,omitempty" xml:"returnCode,omitempty" require:"true"`
  // {'en':'Error message', 'zh_CN':'错误信息'}
  ReturnMsg *string `json:"returnMsg,omitempty" xml:"returnMsg,omitempty" require:"true"`
  // {'en':'content', 'zh_CN':'数据，下面全是数据的内容'}
  Content *CreateUserCreateUserResponseContent `json:"content,omitempty" xml:"content,omitempty" require:"true" type:"Struct"`
}

func (s CreateUserResponse) String() string {
  return tea.Prettify(s)
}

func (s CreateUserResponse) GoString() string {
  return s.String()
}

func (s *CreateUserResponse) SetReturnCode(v string) *CreateUserResponse {
  s.ReturnCode = &v
  return s
}

func (s *CreateUserResponse) SetReturnMsg(v string) *CreateUserResponse {
  s.ReturnMsg = &v
  return s
}

func (s *CreateUserResponse) SetContent(v *CreateUserCreateUserResponseContent) *CreateUserResponse {
  s.Content = v
  return s
}

type CreateUserCreateUserResponseContent struct {
  // {'en':'username', 'zh_CN':'用户名称'}
  Username *string `json:"username,omitempty" xml:"username,omitempty" require:"true"`
  // {'en':'id', 'zh_CN':'用户id'}
  Id *int64 `json:"id,omitempty" xml:"id,omitempty" require:"true"`
  // {'en':'email', 'zh_CN':'邮箱'}
  Email *string `json:"email,omitempty" xml:"email,omitempty" require:"true"`
  // {'en':'areaCode', 'zh_CN':'区号'}
  AreaCode *string `json:"areaCode,omitempty" xml:"areaCode,omitempty" require:"true"`
  // {'en':'cellPhone', 'zh_CN':'手机号'}
  CellPhone *string `json:"cellPhone,omitempty" xml:"cellPhone,omitempty" require:"true"`
  // {'en':'groupId', 'zh_CN':'父组ID'}
  GroupId *int64 `json:"groupId,omitempty" xml:"groupId,omitempty" require:"true"`
  // {'en':'groupName', 'zh_CN':'父组名称'}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty" require:"true"`
  // {'en':'bandwidth', 'zh_CN':'带宽'}
  Bandwidth *string `json:"bandwidth,omitempty" xml:"bandwidth,omitempty" require:"true"`
  // {'en':'remark', 'zh_CN':'备注'}
  Remark *string `json:"remark,omitempty" xml:"remark,omitempty" require:"true"`
  // {'en':'expirationTime', 'zh_CN':'过期时间戳，0-永不过期'}
  ExpirationTime *int64 `json:"expirationTime,omitempty" xml:"expirationTime,omitempty" require:"true"`
  // {'en':'enableUser', 'zh_CN':'启用状态'}
  EnableUser *int `json:"enableUser,omitempty" xml:"enableUser,omitempty" require:"true"`
  // {'en':'smsAuth', 'zh_CN':'短信认证启用'}
  SmsAuth *int `json:"smsAuth,omitempty" xml:"smsAuth,omitempty" require:"true"`
  // {'en':'totpAuth', 'zh_CN':'totp认证启用'}
  TotpAuth *int `json:"totpAuth,omitempty" xml:"totpAuth,omitempty" require:"true"`
  // {'en':'createTime', 'zh_CN':'创建时间戳'}
  CreateTime *int64 `json:"createTime,omitempty" xml:"createTime,omitempty" require:"true"`
}

func (s CreateUserCreateUserResponseContent) String() string {
  return tea.Prettify(s)
}

func (s CreateUserCreateUserResponseContent) GoString() string {
  return s.String()
}

func (s *CreateUserCreateUserResponseContent) SetUsername(v string) *CreateUserCreateUserResponseContent {
  s.Username = &v
  return s
}

func (s *CreateUserCreateUserResponseContent) SetId(v int64) *CreateUserCreateUserResponseContent {
  s.Id = &v
  return s
}

func (s *CreateUserCreateUserResponseContent) SetEmail(v string) *CreateUserCreateUserResponseContent {
  s.Email = &v
  return s
}

func (s *CreateUserCreateUserResponseContent) SetAreaCode(v string) *CreateUserCreateUserResponseContent {
  s.AreaCode = &v
  return s
}

func (s *CreateUserCreateUserResponseContent) SetCellPhone(v string) *CreateUserCreateUserResponseContent {
  s.CellPhone = &v
  return s
}

func (s *CreateUserCreateUserResponseContent) SetGroupId(v int64) *CreateUserCreateUserResponseContent {
  s.GroupId = &v
  return s
}

func (s *CreateUserCreateUserResponseContent) SetGroupName(v string) *CreateUserCreateUserResponseContent {
  s.GroupName = &v
  return s
}

func (s *CreateUserCreateUserResponseContent) SetBandwidth(v string) *CreateUserCreateUserResponseContent {
  s.Bandwidth = &v
  return s
}

func (s *CreateUserCreateUserResponseContent) SetRemark(v string) *CreateUserCreateUserResponseContent {
  s.Remark = &v
  return s
}

func (s *CreateUserCreateUserResponseContent) SetExpirationTime(v int64) *CreateUserCreateUserResponseContent {
  s.ExpirationTime = &v
  return s
}

func (s *CreateUserCreateUserResponseContent) SetEnableUser(v int) *CreateUserCreateUserResponseContent {
  s.EnableUser = &v
  return s
}

func (s *CreateUserCreateUserResponseContent) SetSmsAuth(v int) *CreateUserCreateUserResponseContent {
  s.SmsAuth = &v
  return s
}

func (s *CreateUserCreateUserResponseContent) SetTotpAuth(v int) *CreateUserCreateUserResponseContent {
  s.TotpAuth = &v
  return s
}

func (s *CreateUserCreateUserResponseContent) SetCreateTime(v int64) *CreateUserCreateUserResponseContent {
  s.CreateTime = &v
  return s
}

type CreateUserPaths struct {
}

func (s CreateUserPaths) String() string {
  return tea.Prettify(s)
}

func (s CreateUserPaths) GoString() string {
  return s.String()
}

type CreateUserParameters struct {
}

func (s CreateUserParameters) String() string {
  return tea.Prettify(s)
}

func (s CreateUserParameters) GoString() string {
  return s.String()
}

type CreateUserRequestHeader struct {
}

func (s CreateUserRequestHeader) String() string {
  return tea.Prettify(s)
}

func (s CreateUserRequestHeader) GoString() string {
  return s.String()
}

type CreateUserResponseHeader struct {
}

func (s CreateUserResponseHeader) String() string {
  return tea.Prettify(s)
}

func (s CreateUserResponseHeader) GoString() string {
  return s.String()
}




type ModifyGroupRequest struct {
  // {'en':'User group name
  // This parameter must be specified.', 'zh_CN':'用户组名称'}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty" require:"true"`
  // {'en':'new Group name.
  // The maximum length is 32 characters, and it can be the combination of English, Chinese, and numbers. It cannot contain /', 'zh_CN':'用户组名称
  // 最大长度32个字符，支持英文、中文、数字的组合，不可包含/
  // 该参数必须指定'}
  NewGroupName *string `json:"newGroupName,omitempty" xml:"newGroupName,omitempty"`
  // {'en':'new Parent group name.
  // If the value is '', the group will belongs the root deirectory group.', 'zh_CN':'若传参为&ldquo;&rdquo;，则在根目录下'}
  NewParentGroupName *string `json:"newParentGroupName,omitempty" xml:"newParentGroupName,omitempty"`
  // {'en':'New note
  // Maximum length is 255 characters.', 'zh_CN':'新的备注
  // 最大长度255个字符
  // 不传不修改'}
  Remark *string `json:"remark,omitempty" xml:"remark,omitempty"`
}

func (s ModifyGroupRequest) String() string {
  return tea.Prettify(s)
}

func (s ModifyGroupRequest) GoString() string {
  return s.String()
}

func (s *ModifyGroupRequest) SetGroupName(v string) *ModifyGroupRequest {
  s.GroupName = &v
  return s
}

func (s *ModifyGroupRequest) SetNewGroupName(v string) *ModifyGroupRequest {
  s.NewGroupName = &v
  return s
}

func (s *ModifyGroupRequest) SetNewParentGroupName(v string) *ModifyGroupRequest {
  s.NewParentGroupName = &v
  return s
}

func (s *ModifyGroupRequest) SetRemark(v string) *ModifyGroupRequest {
  s.Remark = &v
  return s
}

type ModifyGroupResponse struct {
  // {'en':'Interface error code, '1' means success', 'zh_CN':'接口错误码，&ldquo;1&rdquo;代表成功'}
  ReturnCode *string `json:"returnCode,omitempty" xml:"returnCode,omitempty" require:"true"`
  // {'en':'Error message', 'zh_CN':'错误信息'}
  ReturnMsg *string `json:"returnMsg,omitempty" xml:"returnMsg,omitempty" require:"true"`
  // {'en':'content', 'zh_CN':'数据，下面全是数据的内容'}
  Content *ModifyGroupModifyGroupResponseContent `json:"content,omitempty" xml:"content,omitempty" require:"true" type:"Struct"`
}

func (s ModifyGroupResponse) String() string {
  return tea.Prettify(s)
}

func (s ModifyGroupResponse) GoString() string {
  return s.String()
}

func (s *ModifyGroupResponse) SetReturnCode(v string) *ModifyGroupResponse {
  s.ReturnCode = &v
  return s
}

func (s *ModifyGroupResponse) SetReturnMsg(v string) *ModifyGroupResponse {
  s.ReturnMsg = &v
  return s
}

func (s *ModifyGroupResponse) SetContent(v *ModifyGroupModifyGroupResponseContent) *ModifyGroupResponse {
  s.Content = v
  return s
}

type ModifyGroupModifyGroupResponseContent struct {
  // {'en':'groupName', 'zh_CN':'用户组名称'}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty" require:"true"`
  // {'en':'groupId', 'zh_CN':'用户组ID'}
  GroupId *int64 `json:"groupId,omitempty" xml:"groupId,omitempty" require:"true"`
  // {'en':'parentGroupName', 'zh_CN':'父组名称'}
  ParentGroupName *string `json:"parentGroupName,omitempty" xml:"parentGroupName,omitempty" require:"true"`
  // {'en':'parentGroupID', 'zh_CN':'父组ID'}
  ParentGroupId *string `json:"parentGroupId,omitempty" xml:"parentGroupId,omitempty" require:"true"`
  // {'en':'remark', 'zh_CN':'备注'}
  Remark *string `json:"remark,omitempty" xml:"remark,omitempty" require:"true"`
  // {'en':'createTime', 'zh_CN':'创建时间'}
  CreateTime *int64 `json:"createTime,omitempty" xml:"createTime,omitempty" require:"true"`
  // {'en':'updateTime', 'zh_CN':'更新时间'}
  UpdateTime *int64 `json:"updateTime,omitempty" xml:"updateTime,omitempty" require:"true"`
}

func (s ModifyGroupModifyGroupResponseContent) String() string {
  return tea.Prettify(s)
}

func (s ModifyGroupModifyGroupResponseContent) GoString() string {
  return s.String()
}

func (s *ModifyGroupModifyGroupResponseContent) SetGroupName(v string) *ModifyGroupModifyGroupResponseContent {
  s.GroupName = &v
  return s
}

func (s *ModifyGroupModifyGroupResponseContent) SetGroupId(v int64) *ModifyGroupModifyGroupResponseContent {
  s.GroupId = &v
  return s
}

func (s *ModifyGroupModifyGroupResponseContent) SetParentGroupName(v string) *ModifyGroupModifyGroupResponseContent {
  s.ParentGroupName = &v
  return s
}

func (s *ModifyGroupModifyGroupResponseContent) SetParentGroupId(v string) *ModifyGroupModifyGroupResponseContent {
  s.ParentGroupId = &v
  return s
}

func (s *ModifyGroupModifyGroupResponseContent) SetRemark(v string) *ModifyGroupModifyGroupResponseContent {
  s.Remark = &v
  return s
}

func (s *ModifyGroupModifyGroupResponseContent) SetCreateTime(v int64) *ModifyGroupModifyGroupResponseContent {
  s.CreateTime = &v
  return s
}

func (s *ModifyGroupModifyGroupResponseContent) SetUpdateTime(v int64) *ModifyGroupModifyGroupResponseContent {
  s.UpdateTime = &v
  return s
}

type ModifyGroupPaths struct {
}

func (s ModifyGroupPaths) String() string {
  return tea.Prettify(s)
}

func (s ModifyGroupPaths) GoString() string {
  return s.String()
}

type ModifyGroupParameters struct {
}

func (s ModifyGroupParameters) String() string {
  return tea.Prettify(s)
}

func (s ModifyGroupParameters) GoString() string {
  return s.String()
}

type ModifyGroupRequestHeader struct {
}

func (s ModifyGroupRequestHeader) String() string {
  return tea.Prettify(s)
}

func (s ModifyGroupRequestHeader) GoString() string {
  return s.String()
}

type ModifyGroupResponseHeader struct {
}

func (s ModifyGroupResponseHeader) String() string {
  return tea.Prettify(s)
}

func (s ModifyGroupResponseHeader) GoString() string {
  return s.String()
}




type CreateGroupRequest struct {
  // {'en':'Group name.
  // The maximum length is 32 characters, and it can be the combination of English, Chinese, and numbers. It cannot contain /
  // This parameter must be specified.', 'zh_CN':'用户组名称
  // 最大长度32个字符，支持英文、中文、数字的组合，不可包含/
  // 该参数必须指定'}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty" require:"true"`
  // {'en':'Parent group name.
  // If the request parameters do not contain this field or it is empty, the group will belongs the root deirectory group.', 'zh_CN':'若传参为空或不传，则在根目录下'}
  ParentGroupName *string `json:"parentGroupName,omitempty" xml:"parentGroupName,omitempty"`
  // {'en':'Note
  // Maximum length is 255 characters.', 'zh_CN':'新的备注
  // 最大长度255个字符'}
  Remark *string `json:"remark,omitempty" xml:"remark,omitempty"`
}

func (s CreateGroupRequest) String() string {
  return tea.Prettify(s)
}

func (s CreateGroupRequest) GoString() string {
  return s.String()
}

func (s *CreateGroupRequest) SetGroupName(v string) *CreateGroupRequest {
  s.GroupName = &v
  return s
}

func (s *CreateGroupRequest) SetParentGroupName(v string) *CreateGroupRequest {
  s.ParentGroupName = &v
  return s
}

func (s *CreateGroupRequest) SetRemark(v string) *CreateGroupRequest {
  s.Remark = &v
  return s
}

type CreateGroupResponse struct {
  // {'en':'Interface error code, 0-fail,1-success', 'zh_CN':'接口错误码，0-代表失败，1-代表成功'}
  ReturnCode *string `json:"returnCode,omitempty" xml:"returnCode,omitempty" require:"true"`
  // {'en':'Error message', 'zh_CN':'错误信息'}
  ReturnMsg *string `json:"returnMsg,omitempty" xml:"returnMsg,omitempty" require:"true"`
  // {'en':'content', 'zh_CN':'数据，下面全是数据的内容'}
  Content *CreateGroupCreateGroupResponseContent `json:"content,omitempty" xml:"content,omitempty" require:"true" type:"Struct"`
}

func (s CreateGroupResponse) String() string {
  return tea.Prettify(s)
}

func (s CreateGroupResponse) GoString() string {
  return s.String()
}

func (s *CreateGroupResponse) SetReturnCode(v string) *CreateGroupResponse {
  s.ReturnCode = &v
  return s
}

func (s *CreateGroupResponse) SetReturnMsg(v string) *CreateGroupResponse {
  s.ReturnMsg = &v
  return s
}

func (s *CreateGroupResponse) SetContent(v *CreateGroupCreateGroupResponseContent) *CreateGroupResponse {
  s.Content = v
  return s
}

type CreateGroupCreateGroupResponseContent struct {
  // {'en':'groupName', 'zh_CN':'用户组名称'}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty" require:"true"`
  // {'en':'groupId', 'zh_CN':'用户组ID'}
  GroupId *int64 `json:"groupId,omitempty" xml:"groupId,omitempty" require:"true"`
  // {'en':'parentGroupName', 'zh_CN':'父组名称'}
  ParentGroupName *string `json:"parentGroupName,omitempty" xml:"parentGroupName,omitempty" require:"true"`
  // {'en':'parentGroupID', 'zh_CN':'父组ID'}
  ParentGroupId *string `json:"parentGroupId,omitempty" xml:"parentGroupId,omitempty" require:"true"`
  // {'en':'remark', 'zh_CN':'备注'}
  Remark *string `json:"remark,omitempty" xml:"remark,omitempty" require:"true"`
  // {'en':'createTime', 'zh_CN':'创建时间'}
  CreateTime *int64 `json:"createTime,omitempty" xml:"createTime,omitempty" require:"true"`
  // {'en':'updateTime', 'zh_CN':'更新时间'}
  UpdateTime *int64 `json:"updateTime,omitempty" xml:"updateTime,omitempty" require:"true"`
}

func (s CreateGroupCreateGroupResponseContent) String() string {
  return tea.Prettify(s)
}

func (s CreateGroupCreateGroupResponseContent) GoString() string {
  return s.String()
}

func (s *CreateGroupCreateGroupResponseContent) SetGroupName(v string) *CreateGroupCreateGroupResponseContent {
  s.GroupName = &v
  return s
}

func (s *CreateGroupCreateGroupResponseContent) SetGroupId(v int64) *CreateGroupCreateGroupResponseContent {
  s.GroupId = &v
  return s
}

func (s *CreateGroupCreateGroupResponseContent) SetParentGroupName(v string) *CreateGroupCreateGroupResponseContent {
  s.ParentGroupName = &v
  return s
}

func (s *CreateGroupCreateGroupResponseContent) SetParentGroupId(v string) *CreateGroupCreateGroupResponseContent {
  s.ParentGroupId = &v
  return s
}

func (s *CreateGroupCreateGroupResponseContent) SetRemark(v string) *CreateGroupCreateGroupResponseContent {
  s.Remark = &v
  return s
}

func (s *CreateGroupCreateGroupResponseContent) SetCreateTime(v int64) *CreateGroupCreateGroupResponseContent {
  s.CreateTime = &v
  return s
}

func (s *CreateGroupCreateGroupResponseContent) SetUpdateTime(v int64) *CreateGroupCreateGroupResponseContent {
  s.UpdateTime = &v
  return s
}

type CreateGroupPaths struct {
}

func (s CreateGroupPaths) String() string {
  return tea.Prettify(s)
}

func (s CreateGroupPaths) GoString() string {
  return s.String()
}

type CreateGroupParameters struct {
}

func (s CreateGroupParameters) String() string {
  return tea.Prettify(s)
}

func (s CreateGroupParameters) GoString() string {
  return s.String()
}

type CreateGroupRequestHeader struct {
}

func (s CreateGroupRequestHeader) String() string {
  return tea.Prettify(s)
}

func (s CreateGroupRequestHeader) GoString() string {
  return s.String()
}

type CreateGroupResponseHeader struct {
}

func (s CreateGroupResponseHeader) String() string {
  return tea.Prettify(s)
}

func (s CreateGroupResponseHeader) GoString() string {
  return s.String()
}




type DescribeUserInfoRequest struct {
}

func (s DescribeUserInfoRequest) String() string {
  return tea.Prettify(s)
}

func (s DescribeUserInfoRequest) GoString() string {
  return s.String()
}

type DescribeUserInfoResponse struct {
  // {'en':'Interface error code, 0-fail,1-success', 'zh_CN':'接口错误码，0-代表失败，1-代表成功'}
  ReturnCode *string `json:"returnCode,omitempty" xml:"returnCode,omitempty" require:"true"`
  // {'en':'Error message', 'zh_CN':'错误信息'}
  ReturnMsg *string `json:"returnMsg,omitempty" xml:"returnMsg,omitempty" require:"true"`
  // {'en':'content', 'zh_CN':'数据，下面全是数据的内容'}
  Content *DescribeUserInfoDescribeUserInfoResponseContent `json:"content,omitempty" xml:"content,omitempty" require:"true" type:"Struct"`
}

func (s DescribeUserInfoResponse) String() string {
  return tea.Prettify(s)
}

func (s DescribeUserInfoResponse) GoString() string {
  return s.String()
}

func (s *DescribeUserInfoResponse) SetReturnCode(v string) *DescribeUserInfoResponse {
  s.ReturnCode = &v
  return s
}

func (s *DescribeUserInfoResponse) SetReturnMsg(v string) *DescribeUserInfoResponse {
  s.ReturnMsg = &v
  return s
}

func (s *DescribeUserInfoResponse) SetContent(v *DescribeUserInfoDescribeUserInfoResponseContent) *DescribeUserInfoResponse {
  s.Content = v
  return s
}

type DescribeUserInfoDescribeUserInfoResponseContent struct {
  // {'en':'username', 'zh_CN':'用户名称'}
  Username *string `json:"username,omitempty" xml:"username,omitempty" require:"true"`
  // {'en':'id', 'zh_CN':'用户id'}
  Id *int64 `json:"id,omitempty" xml:"id,omitempty" require:"true"`
  // {'en':'email', 'zh_CN':'邮箱'}
  Email *string `json:"email,omitempty" xml:"email,omitempty" require:"true"`
  // {'en':'areaCode', 'zh_CN':'区号'}
  AreaCode *string `json:"areaCode,omitempty" xml:"areaCode,omitempty" require:"true"`
  // {'en':'cellPhone', 'zh_CN':'手机号'}
  CellPhone *string `json:"cellPhone,omitempty" xml:"cellPhone,omitempty" require:"true"`
  // {'en':'groupId', 'zh_CN':'父组ID'}
  GroupId *int64 `json:"groupId,omitempty" xml:"groupId,omitempty" require:"true"`
  // {'en':'groupName', 'zh_CN':'父组名称'}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty" require:"true"`
  // {'en':'bandwidth', 'zh_CN':'带宽'}
  Bandwidth *string `json:"bandwidth,omitempty" xml:"bandwidth,omitempty" require:"true"`
  // {'en':'remark', 'zh_CN':'备注'}
  Remark *string `json:"remark,omitempty" xml:"remark,omitempty" require:"true"`
  // {'en':'expirationTime', 'zh_CN':'过期时间戳，0-永不过期'}
  ExpirationTime *int64 `json:"expirationTime,omitempty" xml:"expirationTime,omitempty" require:"true"`
  // {'en':'enableUser', 'zh_CN':'启用状态'}
  EnableUser *int `json:"enableUser,omitempty" xml:"enableUser,omitempty" require:"true"`
  // {'en':'smsAuth', 'zh_CN':'短信认证启用'}
  SmsAuth *int `json:"smsAuth,omitempty" xml:"smsAuth,omitempty" require:"true"`
  // {'en':'totpAuth', 'zh_CN':'totp认证启用'}
  TotpAuth *int `json:"totpAuth,omitempty" xml:"totpAuth,omitempty" require:"true"`
  // {'en':'virtual ip', 'zh_CN':'虚拟ip'}
  Vip *string `json:"vip,omitempty" xml:"vip,omitempty" require:"true"`
  // {'en':'createTime', 'zh_CN':'创建时间戳'}
  CreateTime *int64 `json:"createTime,omitempty" xml:"createTime,omitempty" require:"true"`
}

func (s DescribeUserInfoDescribeUserInfoResponseContent) String() string {
  return tea.Prettify(s)
}

func (s DescribeUserInfoDescribeUserInfoResponseContent) GoString() string {
  return s.String()
}

func (s *DescribeUserInfoDescribeUserInfoResponseContent) SetUsername(v string) *DescribeUserInfoDescribeUserInfoResponseContent {
  s.Username = &v
  return s
}

func (s *DescribeUserInfoDescribeUserInfoResponseContent) SetId(v int64) *DescribeUserInfoDescribeUserInfoResponseContent {
  s.Id = &v
  return s
}

func (s *DescribeUserInfoDescribeUserInfoResponseContent) SetEmail(v string) *DescribeUserInfoDescribeUserInfoResponseContent {
  s.Email = &v
  return s
}

func (s *DescribeUserInfoDescribeUserInfoResponseContent) SetAreaCode(v string) *DescribeUserInfoDescribeUserInfoResponseContent {
  s.AreaCode = &v
  return s
}

func (s *DescribeUserInfoDescribeUserInfoResponseContent) SetCellPhone(v string) *DescribeUserInfoDescribeUserInfoResponseContent {
  s.CellPhone = &v
  return s
}

func (s *DescribeUserInfoDescribeUserInfoResponseContent) SetGroupId(v int64) *DescribeUserInfoDescribeUserInfoResponseContent {
  s.GroupId = &v
  return s
}

func (s *DescribeUserInfoDescribeUserInfoResponseContent) SetGroupName(v string) *DescribeUserInfoDescribeUserInfoResponseContent {
  s.GroupName = &v
  return s
}

func (s *DescribeUserInfoDescribeUserInfoResponseContent) SetBandwidth(v string) *DescribeUserInfoDescribeUserInfoResponseContent {
  s.Bandwidth = &v
  return s
}

func (s *DescribeUserInfoDescribeUserInfoResponseContent) SetRemark(v string) *DescribeUserInfoDescribeUserInfoResponseContent {
  s.Remark = &v
  return s
}

func (s *DescribeUserInfoDescribeUserInfoResponseContent) SetExpirationTime(v int64) *DescribeUserInfoDescribeUserInfoResponseContent {
  s.ExpirationTime = &v
  return s
}

func (s *DescribeUserInfoDescribeUserInfoResponseContent) SetEnableUser(v int) *DescribeUserInfoDescribeUserInfoResponseContent {
  s.EnableUser = &v
  return s
}

func (s *DescribeUserInfoDescribeUserInfoResponseContent) SetSmsAuth(v int) *DescribeUserInfoDescribeUserInfoResponseContent {
  s.SmsAuth = &v
  return s
}

func (s *DescribeUserInfoDescribeUserInfoResponseContent) SetTotpAuth(v int) *DescribeUserInfoDescribeUserInfoResponseContent {
  s.TotpAuth = &v
  return s
}

func (s *DescribeUserInfoDescribeUserInfoResponseContent) SetVip(v string) *DescribeUserInfoDescribeUserInfoResponseContent {
  s.Vip = &v
  return s
}

func (s *DescribeUserInfoDescribeUserInfoResponseContent) SetCreateTime(v int64) *DescribeUserInfoDescribeUserInfoResponseContent {
  s.CreateTime = &v
  return s
}

type DescribeUserInfoPaths struct {
}

func (s DescribeUserInfoPaths) String() string {
  return tea.Prettify(s)
}

func (s DescribeUserInfoPaths) GoString() string {
  return s.String()
}

type DescribeUserInfoParameters struct {
  // {'en':'username', 'zh_CN':'用户名'}
  Username *string `json:"username,omitempty" xml:"username,omitempty" require:"true"`
}

func (s DescribeUserInfoParameters) String() string {
  return tea.Prettify(s)
}

func (s DescribeUserInfoParameters) GoString() string {
  return s.String()
}

func (s *DescribeUserInfoParameters) SetUsername(v string) *DescribeUserInfoParameters {
  s.Username = &v
  return s
}

type DescribeUserInfoRequestHeader struct {
}

func (s DescribeUserInfoRequestHeader) String() string {
  return tea.Prettify(s)
}

func (s DescribeUserInfoRequestHeader) GoString() string {
  return s.String()
}

type DescribeUserInfoResponseHeader struct {
}

func (s DescribeUserInfoResponseHeader) String() string {
  return tea.Prettify(s)
}

func (s DescribeUserInfoResponseHeader) GoString() string {
  return s.String()
}




type DeleteGroupRequest struct {
  // {'en':'User group name', 'zh_CN':'用户组名称'}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty" require:"true"`
}

func (s DeleteGroupRequest) String() string {
  return tea.Prettify(s)
}

func (s DeleteGroupRequest) GoString() string {
  return s.String()
}

func (s *DeleteGroupRequest) SetGroupName(v string) *DeleteGroupRequest {
  s.GroupName = &v
  return s
}

type DeleteGroupResponse struct {
  // {'en':'Interface error code, 0-fail,1-success', 'zh_CN':'接口错误码，0-代表失败，1-代表成功'}
  ReturnCode *string `json:"returnCode,omitempty" xml:"returnCode,omitempty" require:"true"`
  // {'en':'Error message', 'zh_CN':'错误信息'}
  ReturnMsg *string `json:"returnMsg,omitempty" xml:"returnMsg,omitempty" require:"true"`
}

func (s DeleteGroupResponse) String() string {
  return tea.Prettify(s)
}

func (s DeleteGroupResponse) GoString() string {
  return s.String()
}

func (s *DeleteGroupResponse) SetReturnCode(v string) *DeleteGroupResponse {
  s.ReturnCode = &v
  return s
}

func (s *DeleteGroupResponse) SetReturnMsg(v string) *DeleteGroupResponse {
  s.ReturnMsg = &v
  return s
}

type DeleteGroupPaths struct {
}

func (s DeleteGroupPaths) String() string {
  return tea.Prettify(s)
}

func (s DeleteGroupPaths) GoString() string {
  return s.String()
}

type DeleteGroupParameters struct {
}

func (s DeleteGroupParameters) String() string {
  return tea.Prettify(s)
}

func (s DeleteGroupParameters) GoString() string {
  return s.String()
}

type DeleteGroupRequestHeader struct {
}

func (s DeleteGroupRequestHeader) String() string {
  return tea.Prettify(s)
}

func (s DeleteGroupRequestHeader) GoString() string {
  return s.String()
}

type DeleteGroupResponseHeader struct {
}

func (s DeleteGroupResponseHeader) String() string {
  return tea.Prettify(s)
}

func (s DeleteGroupResponseHeader) GoString() string {
  return s.String()
}




type ModifyuserRequest struct {
  // {'en':'Username of the specific user.', 'zh_CN':'需要修改的用户'}
  Username *string `json:"username,omitempty" xml:"username,omitempty" require:"true"`
  // {'en':'Parent group name', 'zh_CN':'父组名称'}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty"`
  // {'en':'Area code
  // If the areaCode is null and when cellPhone is not null, areaCode  will be 86.', 'zh_CN':'区号，手机号存在但区号不存在时会默认设置86'}
  AreaCode *string `json:"areaCode,omitempty" xml:"areaCode,omitempty"`
  // {'en':'Mobile', 'zh_CN':'手机号'}
  CellPhone *string `json:"cellPhone,omitempty" xml:"cellPhone,omitempty"`
  // {'en':'MFA: message authentication, default 0
  // 0: off,
  // 1:  on', 'zh_CN':'双因子认证 : 短信认证，默认0
  // 0 关闭， 1 开启'}
  SmsAuth *int `json:"smsAuth,omitempty" xml:"smsAuth,omitempty"`
  // {'en':'MFA: totp authentication, default 0
  // 0: off,
  // 1:  on', 'zh_CN':'双因子认证 : totp认证，默认0
  // 0 关闭， 1 开启'}
  TotpAuth *int `json:"totpAuth,omitempty" xml:"totpAuth,omitempty"`
  // {'en':'Mail.', 'zh_CN':'邮箱'}
  Email *string `json:"email,omitempty" xml:"email,omitempty"`
  // {'en':'Expiration time, pass timestamp, millisecond level, do not pass as 0
  // 0: never expire
  // 1626732871372: Set expiration time', 'zh_CN':'过期时间，传时间戳，毫秒级别，不传为0
  // 0：永不过期
  // 1626732871372：设置过期时间'}
  ExpireTime *int64 `json:"expireTime,omitempty" xml:"expireTime,omitempty"`
  // {'en':'Whether to enable the user, do not pass the parameter to enable
  // 1: enable
  // 0: disable', 'zh_CN':'是否启用用户，不传参为启用
  // 1:启用
  // 0:禁用'}
  EnableStatus *int `json:"enableStatus,omitempty" xml:"enableStatus,omitempty"`
  // {'en':'New note
  // Maximum length is 255 characters.', 'zh_CN':'新的备注
  // 最大长度255个字符'}
  Remark *string `json:"remark,omitempty" xml:"remark,omitempty"`
  // {'en':'Bandwidth limit
  // No parameter transmission is 1/2{max bandwidth}
  // If the parameter transmission exceeds the maximum bandwidth, it is {maximum bandwidth}', 'zh_CN':'带宽限制
  // 不传参为 1/2{最大带宽}
  // 传参超过最大带宽，则为{最大带宽}'}
  Bandwidth *float64 `json:"bandwidth,omitempty" xml:"bandwidth,omitempty"`
}

func (s ModifyuserRequest) String() string {
  return tea.Prettify(s)
}

func (s ModifyuserRequest) GoString() string {
  return s.String()
}

func (s *ModifyuserRequest) SetUsername(v string) *ModifyuserRequest {
  s.Username = &v
  return s
}

func (s *ModifyuserRequest) SetGroupName(v string) *ModifyuserRequest {
  s.GroupName = &v
  return s
}

func (s *ModifyuserRequest) SetAreaCode(v string) *ModifyuserRequest {
  s.AreaCode = &v
  return s
}

func (s *ModifyuserRequest) SetCellPhone(v string) *ModifyuserRequest {
  s.CellPhone = &v
  return s
}

func (s *ModifyuserRequest) SetSmsAuth(v int) *ModifyuserRequest {
  s.SmsAuth = &v
  return s
}

func (s *ModifyuserRequest) SetTotpAuth(v int) *ModifyuserRequest {
  s.TotpAuth = &v
  return s
}

func (s *ModifyuserRequest) SetEmail(v string) *ModifyuserRequest {
  s.Email = &v
  return s
}

func (s *ModifyuserRequest) SetExpireTime(v int64) *ModifyuserRequest {
  s.ExpireTime = &v
  return s
}

func (s *ModifyuserRequest) SetEnableStatus(v int) *ModifyuserRequest {
  s.EnableStatus = &v
  return s
}

func (s *ModifyuserRequest) SetRemark(v string) *ModifyuserRequest {
  s.Remark = &v
  return s
}

func (s *ModifyuserRequest) SetBandwidth(v float64) *ModifyuserRequest {
  s.Bandwidth = &v
  return s
}

type ModifyuserResponse struct {
  // {'en':'Interface error code, 0-fail,1-success', 'zh_CN':'接口错误码，0-代表失败，1-代表成功'}
  ReturnCode *string `json:"returnCode,omitempty" xml:"returnCode,omitempty" require:"true"`
  // {'en':'Error message', 'zh_CN':'错误信息'}
  ReturnMsg *string `json:"returnMsg,omitempty" xml:"returnMsg,omitempty" require:"true"`
  // {'en':'content', 'zh_CN':'数据，下面全是数据的内容'}
  Content *ModifyuserModifyuserResponseContent `json:"content,omitempty" xml:"content,omitempty" require:"true" type:"Struct"`
}

func (s ModifyuserResponse) String() string {
  return tea.Prettify(s)
}

func (s ModifyuserResponse) GoString() string {
  return s.String()
}

func (s *ModifyuserResponse) SetReturnCode(v string) *ModifyuserResponse {
  s.ReturnCode = &v
  return s
}

func (s *ModifyuserResponse) SetReturnMsg(v string) *ModifyuserResponse {
  s.ReturnMsg = &v
  return s
}

func (s *ModifyuserResponse) SetContent(v *ModifyuserModifyuserResponseContent) *ModifyuserResponse {
  s.Content = v
  return s
}

type ModifyuserModifyuserResponseContent struct {
  // {'en':'username', 'zh_CN':'用户名称'}
  Username *string `json:"username,omitempty" xml:"username,omitempty" require:"true"`
  // {'en':'id', 'zh_CN':'用户id'}
  Id *int64 `json:"id,omitempty" xml:"id,omitempty" require:"true"`
  // {'en':'email', 'zh_CN':'邮箱'}
  Email *string `json:"email,omitempty" xml:"email,omitempty" require:"true"`
  // {'en':'areaCode', 'zh_CN':'区号'}
  AreaCode *string `json:"areaCode,omitempty" xml:"areaCode,omitempty" require:"true"`
  // {'en':'cellPhone', 'zh_CN':'手机号'}
  CellPhone *string `json:"cellPhone,omitempty" xml:"cellPhone,omitempty" require:"true"`
  // {'en':'groupId', 'zh_CN':'父组Id'}
  GroupId *int64 `json:"groupId,omitempty" xml:"groupId,omitempty" require:"true"`
  // {'en':'groupName', 'zh_CN':'父组名称'}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty" require:"true"`
  // {'en':'bandwidth', 'zh_CN':'带宽'}
  Bandwidth *string `json:"bandwidth,omitempty" xml:"bandwidth,omitempty" require:"true"`
  // {'en':'remark', 'zh_CN':'备注'}
  Remark *string `json:"remark,omitempty" xml:"remark,omitempty" require:"true"`
  // {'en':'expirationTime', 'zh_CN':'过期时间戳，0-永不过期'}
  ExpirationTime *int64 `json:"expirationTime,omitempty" xml:"expirationTime,omitempty" require:"true"`
  // {'en':'enableUser', 'zh_CN':'启用状态'}
  EnableUser *int `json:"enableUser,omitempty" xml:"enableUser,omitempty" require:"true"`
  // {'en':'smsAuth', 'zh_CN':'短信认证启用'}
  SmsAuth *int `json:"smsAuth,omitempty" xml:"smsAuth,omitempty" require:"true"`
  // {'en':'totpAuth', 'zh_CN':'totp认证启用'}
  TotpAuth *int `json:"totpAuth,omitempty" xml:"totpAuth,omitempty" require:"true"`
  // {'en':'createTime', 'zh_CN':'创建时间戳'}
  CreateTime *int64 `json:"createTime,omitempty" xml:"createTime,omitempty" require:"true"`
}

func (s ModifyuserModifyuserResponseContent) String() string {
  return tea.Prettify(s)
}

func (s ModifyuserModifyuserResponseContent) GoString() string {
  return s.String()
}

func (s *ModifyuserModifyuserResponseContent) SetUsername(v string) *ModifyuserModifyuserResponseContent {
  s.Username = &v
  return s
}

func (s *ModifyuserModifyuserResponseContent) SetId(v int64) *ModifyuserModifyuserResponseContent {
  s.Id = &v
  return s
}

func (s *ModifyuserModifyuserResponseContent) SetEmail(v string) *ModifyuserModifyuserResponseContent {
  s.Email = &v
  return s
}

func (s *ModifyuserModifyuserResponseContent) SetAreaCode(v string) *ModifyuserModifyuserResponseContent {
  s.AreaCode = &v
  return s
}

func (s *ModifyuserModifyuserResponseContent) SetCellPhone(v string) *ModifyuserModifyuserResponseContent {
  s.CellPhone = &v
  return s
}

func (s *ModifyuserModifyuserResponseContent) SetGroupId(v int64) *ModifyuserModifyuserResponseContent {
  s.GroupId = &v
  return s
}

func (s *ModifyuserModifyuserResponseContent) SetGroupName(v string) *ModifyuserModifyuserResponseContent {
  s.GroupName = &v
  return s
}

func (s *ModifyuserModifyuserResponseContent) SetBandwidth(v string) *ModifyuserModifyuserResponseContent {
  s.Bandwidth = &v
  return s
}

func (s *ModifyuserModifyuserResponseContent) SetRemark(v string) *ModifyuserModifyuserResponseContent {
  s.Remark = &v
  return s
}

func (s *ModifyuserModifyuserResponseContent) SetExpirationTime(v int64) *ModifyuserModifyuserResponseContent {
  s.ExpirationTime = &v
  return s
}

func (s *ModifyuserModifyuserResponseContent) SetEnableUser(v int) *ModifyuserModifyuserResponseContent {
  s.EnableUser = &v
  return s
}

func (s *ModifyuserModifyuserResponseContent) SetSmsAuth(v int) *ModifyuserModifyuserResponseContent {
  s.SmsAuth = &v
  return s
}

func (s *ModifyuserModifyuserResponseContent) SetTotpAuth(v int) *ModifyuserModifyuserResponseContent {
  s.TotpAuth = &v
  return s
}

func (s *ModifyuserModifyuserResponseContent) SetCreateTime(v int64) *ModifyuserModifyuserResponseContent {
  s.CreateTime = &v
  return s
}

type ModifyuserPaths struct {
}

func (s ModifyuserPaths) String() string {
  return tea.Prettify(s)
}

func (s ModifyuserPaths) GoString() string {
  return s.String()
}

type ModifyuserParameters struct {
}

func (s ModifyuserParameters) String() string {
  return tea.Prettify(s)
}

func (s ModifyuserParameters) GoString() string {
  return s.String()
}

type ModifyuserRequestHeader struct {
}

func (s ModifyuserRequestHeader) String() string {
  return tea.Prettify(s)
}

func (s ModifyuserRequestHeader) GoString() string {
  return s.String()
}

type ModifyuserResponseHeader struct {
}

func (s ModifyuserResponseHeader) String() string {
  return tea.Prettify(s)
}

func (s ModifyuserResponseHeader) GoString() string {
  return s.String()
}




type SyncAuthConfigRequest struct {
  // {"en":"auth config name", "zh_CN":"身份源名称"}
  AuthConfigName *string `json:"authConfigName,omitempty" xml:"authConfigName,omitempty" require:"true"`
}

func (s SyncAuthConfigRequest) String() string {
  return tea.Prettify(s)
}

func (s SyncAuthConfigRequest) GoString() string {
  return s.String()
}

func (s *SyncAuthConfigRequest) SetAuthConfigName(v string) *SyncAuthConfigRequest {
  s.AuthConfigName = &v
  return s
}

type SyncAuthConfigResponse struct {
  // {"en":"Interface error code, 0-fail,1-success", "zh_CN":"接口错误码，0-代表失败，1-代表成功"}
  ReturnCode *string `json:"returnCode,omitempty" xml:"returnCode,omitempty" require:"true"`
  // {"en":"Error message", "zh_CN":"错误信息"}
  ReturnMsg *string `json:"returnMsg,omitempty" xml:"returnMsg,omitempty" require:"true"`
}

func (s SyncAuthConfigResponse) String() string {
  return tea.Prettify(s)
}

func (s SyncAuthConfigResponse) GoString() string {
  return s.String()
}

func (s *SyncAuthConfigResponse) SetReturnCode(v string) *SyncAuthConfigResponse {
  s.ReturnCode = &v
  return s
}

func (s *SyncAuthConfigResponse) SetReturnMsg(v string) *SyncAuthConfigResponse {
  s.ReturnMsg = &v
  return s
}

type SyncAuthConfigPaths struct {
}

func (s SyncAuthConfigPaths) String() string {
  return tea.Prettify(s)
}

func (s SyncAuthConfigPaths) GoString() string {
  return s.String()
}

type SyncAuthConfigParameters struct {
}

func (s SyncAuthConfigParameters) String() string {
  return tea.Prettify(s)
}

func (s SyncAuthConfigParameters) GoString() string {
  return s.String()
}

type SyncAuthConfigRequestHeader struct {
  // {"en":"uac account name", "zh_CN":"当前企业的UAC主账号名"}
  AuthUser *string `json:"authUser,omitempty" xml:"authUser,omitempty" require:"true"`
}

func (s SyncAuthConfigRequestHeader) String() string {
  return tea.Prettify(s)
}

func (s SyncAuthConfigRequestHeader) GoString() string {
  return s.String()
}

func (s *SyncAuthConfigRequestHeader) SetAuthUser(v string) *SyncAuthConfigRequestHeader {
  s.AuthUser = &v
  return s
}

type SyncAuthConfigResponseHeader struct {
}

func (s SyncAuthConfigResponseHeader) String() string {
  return tea.Prettify(s)
}

func (s SyncAuthConfigResponseHeader) GoString() string {
  return s.String()
}




type DeleteuserRequest struct {
  // {'en':'username
  // This parameter must be specified.', 'zh_CN':'用户名
  // 该参数必须指定。'}
  Username *string `json:"username,omitempty" xml:"username,omitempty" require:"true"`
}

func (s DeleteuserRequest) String() string {
  return tea.Prettify(s)
}

func (s DeleteuserRequest) GoString() string {
  return s.String()
}

func (s *DeleteuserRequest) SetUsername(v string) *DeleteuserRequest {
  s.Username = &v
  return s
}

type DeleteuserResponse struct {
  // {'en':'Interface error code, 0-fail,1-success', 'zh_CN':'接口错误码，0-代表失败，1-代表成功'}
  ReturnCode *string `json:"returnCode,omitempty" xml:"returnCode,omitempty" require:"true"`
  // {'en':'Error message', 'zh_CN':'错误信息'}
  ReturnMsg *string `json:"returnMsg,omitempty" xml:"returnMsg,omitempty" require:"true"`
}

func (s DeleteuserResponse) String() string {
  return tea.Prettify(s)
}

func (s DeleteuserResponse) GoString() string {
  return s.String()
}

func (s *DeleteuserResponse) SetReturnCode(v string) *DeleteuserResponse {
  s.ReturnCode = &v
  return s
}

func (s *DeleteuserResponse) SetReturnMsg(v string) *DeleteuserResponse {
  s.ReturnMsg = &v
  return s
}

type DeleteuserPaths struct {
}

func (s DeleteuserPaths) String() string {
  return tea.Prettify(s)
}

func (s DeleteuserPaths) GoString() string {
  return s.String()
}

type DeleteuserParameters struct {
}

func (s DeleteuserParameters) String() string {
  return tea.Prettify(s)
}

func (s DeleteuserParameters) GoString() string {
  return s.String()
}

type DeleteuserRequestHeader struct {
}

func (s DeleteuserRequestHeader) String() string {
  return tea.Prettify(s)
}

func (s DeleteuserRequestHeader) GoString() string {
  return s.String()
}

type DeleteuserResponseHeader struct {
}

func (s DeleteuserResponseHeader) String() string {
  return tea.Prettify(s)
}

func (s DeleteuserResponseHeader) GoString() string {
  return s.String()
}




type ListGroupsRequest struct {
}

func (s ListGroupsRequest) String() string {
  return tea.Prettify(s)
}

func (s ListGroupsRequest) GoString() string {
  return s.String()
}

type ListGroupsResponse struct {
  // {'en':'Interface error code, 0-fail,1-success', 'zh_CN':'接口错误码，0-代表失败，1-代表成功'}
  ReturnCode *string `json:"returnCode,omitempty" xml:"returnCode,omitempty" require:"true"`
  // {'en':'Error message', 'zh_CN':'错误信息'}
  ReturnMsg *string `json:"returnMsg,omitempty" xml:"returnMsg,omitempty" require:"true"`
  // {'en':'content', 'zh_CN':'数据，下面全是数据的内容'}
  Content *ListGroupsListGroupsResponseContent `json:"content,omitempty" xml:"content,omitempty" require:"true" type:"Struct"`
}

func (s ListGroupsResponse) String() string {
  return tea.Prettify(s)
}

func (s ListGroupsResponse) GoString() string {
  return s.String()
}

func (s *ListGroupsResponse) SetReturnCode(v string) *ListGroupsResponse {
  s.ReturnCode = &v
  return s
}

func (s *ListGroupsResponse) SetReturnMsg(v string) *ListGroupsResponse {
  s.ReturnMsg = &v
  return s
}

func (s *ListGroupsResponse) SetContent(v *ListGroupsListGroupsResponseContent) *ListGroupsResponse {
  s.Content = v
  return s
}

type ListGroupsListGroupsResponseContent struct {
  // {'en':'groupList', 'zh_CN':'group集合，下面为字段'}
  GroupList []*ListGroupsListGroupsResponseContentGroupList `json:"groupList,omitempty" xml:"groupList,omitempty" require:"true" type:"Repeated"`
}

func (s ListGroupsListGroupsResponseContent) String() string {
  return tea.Prettify(s)
}

func (s ListGroupsListGroupsResponseContent) GoString() string {
  return s.String()
}

func (s *ListGroupsListGroupsResponseContent) SetGroupList(v []*ListGroupsListGroupsResponseContentGroupList) *ListGroupsListGroupsResponseContent {
  s.GroupList = v
  return s
}

type ListGroupsListGroupsResponseContentGroupList struct     {
  // {'en':'groupName', 'zh_CN':'用户组名称'}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty" require:"true"`
  // {'en':'groupId', 'zh_CN':'用户组ID'}
  GroupId *int64 `json:"groupId,omitempty" xml:"groupId,omitempty" require:"true"`
  // {'en':'parentGroupName', 'zh_CN':'父组名称'}
  ParentGroupName *string `json:"parentGroupName,omitempty" xml:"parentGroupName,omitempty" require:"true"`
  // {'en':'parentGroupID', 'zh_CN':'父组ID'}
  ParentGroupId *string `json:"parentGroupId,omitempty" xml:"parentGroupId,omitempty" require:"true"`
  // {'en':'authConfigName', 'zh_CN':'所属组织架构名称'}
  AuthConfigName *string `json:"authConfigName,omitempty" xml:"authConfigName,omitempty" require:"true"`
  // {'en':'remark', 'zh_CN':'备注'}
  Remark *string `json:"remark,omitempty" xml:"remark,omitempty" require:"true"`
  // {'en':'createTime', 'zh_CN':'创建时间'}
  CreateTime *int64 `json:"createTime,omitempty" xml:"createTime,omitempty" require:"true"`
  // {'en':'updateTime', 'zh_CN':'更新时间'}
  UpdateTime *int64 `json:"updateTime,omitempty" xml:"updateTime,omitempty" require:"true"`
}

func (s ListGroupsListGroupsResponseContentGroupList) String() string {
  return tea.Prettify(s)
}

func (s ListGroupsListGroupsResponseContentGroupList) GoString() string {
  return s.String()
}

func (s *ListGroupsListGroupsResponseContentGroupList) SetGroupName(v string) *ListGroupsListGroupsResponseContentGroupList {
  s.GroupName = &v
  return s
}

func (s *ListGroupsListGroupsResponseContentGroupList) SetGroupId(v int64) *ListGroupsListGroupsResponseContentGroupList {
  s.GroupId = &v
  return s
}

func (s *ListGroupsListGroupsResponseContentGroupList) SetParentGroupName(v string) *ListGroupsListGroupsResponseContentGroupList {
  s.ParentGroupName = &v
  return s
}

func (s *ListGroupsListGroupsResponseContentGroupList) SetParentGroupId(v string) *ListGroupsListGroupsResponseContentGroupList {
  s.ParentGroupId = &v
  return s
}

func (s *ListGroupsListGroupsResponseContentGroupList) SetAuthConfigName(v string) *ListGroupsListGroupsResponseContentGroupList {
  s.AuthConfigName = &v
  return s
}

func (s *ListGroupsListGroupsResponseContentGroupList) SetRemark(v string) *ListGroupsListGroupsResponseContentGroupList {
  s.Remark = &v
  return s
}

func (s *ListGroupsListGroupsResponseContentGroupList) SetCreateTime(v int64) *ListGroupsListGroupsResponseContentGroupList {
  s.CreateTime = &v
  return s
}

func (s *ListGroupsListGroupsResponseContentGroupList) SetUpdateTime(v int64) *ListGroupsListGroupsResponseContentGroupList {
  s.UpdateTime = &v
  return s
}

type ListGroupsPaths struct {
}

func (s ListGroupsPaths) String() string {
  return tea.Prettify(s)
}

func (s ListGroupsPaths) GoString() string {
  return s.String()
}

type ListGroupsParameters struct {
  // {'en':'Query all user groups under the specified parent group.
  // If the value is null, query all groups under the root directory group.', 'zh_CN':'查询指定父组下的所有用户组
  // 不填写时，查全部'}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty"`
}

func (s ListGroupsParameters) String() string {
  return tea.Prettify(s)
}

func (s ListGroupsParameters) GoString() string {
  return s.String()
}

func (s *ListGroupsParameters) SetGroupName(v string) *ListGroupsParameters {
  s.GroupName = &v
  return s
}

type ListGroupsRequestHeader struct {
}

func (s ListGroupsRequestHeader) String() string {
  return tea.Prettify(s)
}

func (s ListGroupsRequestHeader) GoString() string {
  return s.String()
}

type ListGroupsResponseHeader struct {
}

func (s ListGroupsResponseHeader) String() string {
  return tea.Prettify(s)
}

func (s ListGroupsResponseHeader) GoString() string {
  return s.String()
}




type ListUsersRequest struct {
}

func (s ListUsersRequest) String() string {
  return tea.Prettify(s)
}

func (s ListUsersRequest) GoString() string {
  return s.String()
}

type ListUsersResponse struct {
  // {'en':'Interface error code, 0-fail,1-success', 'zh_CN':'接口错误码，0-代表失败，1-代表成功'}
  ReturnCode *string `json:"returnCode,omitempty" xml:"returnCode,omitempty" require:"true"`
  // {'en':'Error message', 'zh_CN':'错误信息'}
  ReturnMsg *string `json:"returnMsg,omitempty" xml:"returnMsg,omitempty" require:"true"`
  // {'en':'content', 'zh_CN':'数据，下面全是数据的内容'}
  Content *ListUsersListUsersResponseContent `json:"content,omitempty" xml:"content,omitempty" require:"true" type:"Struct"`
}

func (s ListUsersResponse) String() string {
  return tea.Prettify(s)
}

func (s ListUsersResponse) GoString() string {
  return s.String()
}

func (s *ListUsersResponse) SetReturnCode(v string) *ListUsersResponse {
  s.ReturnCode = &v
  return s
}

func (s *ListUsersResponse) SetReturnMsg(v string) *ListUsersResponse {
  s.ReturnMsg = &v
  return s
}

func (s *ListUsersResponse) SetContent(v *ListUsersListUsersResponseContent) *ListUsersResponse {
  s.Content = v
  return s
}

type ListUsersListUsersResponseContent struct {
  // {'en':'pageSize', 'zh_CN':'输入时设置的每页行数'}
  PageSize *int `json:"pageSize,omitempty" xml:"pageSize,omitempty" require:"true"`
  // {'en':'pageNo', 'zh_CN':'用户列表的页码'}
  PageNo *int `json:"pageNo,omitempty" xml:"pageNo,omitempty" require:"true"`
  // {'en':'totalCount', 'zh_CN':'实例总数'}
  TotalCount *int `json:"totalCount,omitempty" xml:"totalCount,omitempty" require:"true"`
  // {'en':'result', 'zh_CN':'分页结果数据，下面为数据格式'}
  Result *ListUsersListUsersResponseContentResult `json:"result,omitempty" xml:"result,omitempty" require:"true" type:"Struct"`
}

func (s ListUsersListUsersResponseContent) String() string {
  return tea.Prettify(s)
}

func (s ListUsersListUsersResponseContent) GoString() string {
  return s.String()
}

func (s *ListUsersListUsersResponseContent) SetPageSize(v int) *ListUsersListUsersResponseContent {
  s.PageSize = &v
  return s
}

func (s *ListUsersListUsersResponseContent) SetPageNo(v int) *ListUsersListUsersResponseContent {
  s.PageNo = &v
  return s
}

func (s *ListUsersListUsersResponseContent) SetTotalCount(v int) *ListUsersListUsersResponseContent {
  s.TotalCount = &v
  return s
}

func (s *ListUsersListUsersResponseContent) SetResult(v *ListUsersListUsersResponseContentResult) *ListUsersListUsersResponseContent {
  s.Result = v
  return s
}

type ListUsersListUsersResponseContentResult struct {
  // {'en':'username', 'zh_CN':'用户名称'}
  Username *string `json:"username,omitempty" xml:"username,omitempty" require:"true"`
  // {'en':'id', 'zh_CN':'用户id'}
  Id *int64 `json:"id,omitempty" xml:"id,omitempty" require:"true"`
  // {'en':'email', 'zh_CN':'邮箱'}
  Email *string `json:"email,omitempty" xml:"email,omitempty" require:"true"`
  // {'en':'areaCode', 'zh_CN':'区号'}
  AreaCode *string `json:"areaCode,omitempty" xml:"areaCode,omitempty" require:"true"`
  // {'en':'cellphone', 'zh_CN':'手机号'}
  Cellphone *string `json:"cellphone,omitempty" xml:"cellphone,omitempty" require:"true"`
  // {'en':'groupID', 'zh_CN':'父组ID'}
  GroupId *int64 `json:"groupId,omitempty" xml:"groupId,omitempty" require:"true"`
  // {'en':'groupName', 'zh_CN':'父组名称'}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty" require:"true"`
  // {'en':'bandwidth', 'zh_CN':'带宽'}
  Bandwidth *string `json:"bandwidth,omitempty" xml:"bandwidth,omitempty" require:"true"`
  // {'en':'remark', 'zh_CN':'备注'}
  Remark *string `json:"remark,omitempty" xml:"remark,omitempty" require:"true"`
  // {'en':'expireTime', 'zh_CN':'过期时间戳，0-永不过期'}
  ExpireTime *int64 `json:"expireTime,omitempty" xml:"expireTime,omitempty" require:"true"`
  // {'en':'enableStatus', 'zh_CN':'启用状态,-1：禁用，0：启用但离线，2：启用且在线'}
  EnableStatus *int `json:"enableStatus,omitempty" xml:"enableStatus,omitempty" require:"true"`
  // {'en':'smsAuth', 'zh_CN':'短信认证启用'}
  SmsAuth *int `json:"smsAuth,omitempty" xml:"smsAuth,omitempty" require:"true"`
  // {'en':'totpAuth', 'zh_CN':'totp认证启用'}
  TotpAuth *int `json:"totpAuth,omitempty" xml:"totpAuth,omitempty" require:"true"`
  // {'en':'virtual ip', 'zh_CN':'虚拟ip'}
  Vip *string `json:"vip,omitempty" xml:"vip,omitempty" require:"true"`
  // {'en':'createTime', 'zh_CN':'创建时间戳'}
  CreateTime *int64 `json:"createTime,omitempty" xml:"createTime,omitempty" require:"true"`
}

func (s ListUsersListUsersResponseContentResult) String() string {
  return tea.Prettify(s)
}

func (s ListUsersListUsersResponseContentResult) GoString() string {
  return s.String()
}

func (s *ListUsersListUsersResponseContentResult) SetUsername(v string) *ListUsersListUsersResponseContentResult {
  s.Username = &v
  return s
}

func (s *ListUsersListUsersResponseContentResult) SetId(v int64) *ListUsersListUsersResponseContentResult {
  s.Id = &v
  return s
}

func (s *ListUsersListUsersResponseContentResult) SetEmail(v string) *ListUsersListUsersResponseContentResult {
  s.Email = &v
  return s
}

func (s *ListUsersListUsersResponseContentResult) SetAreaCode(v string) *ListUsersListUsersResponseContentResult {
  s.AreaCode = &v
  return s
}

func (s *ListUsersListUsersResponseContentResult) SetCellphone(v string) *ListUsersListUsersResponseContentResult {
  s.Cellphone = &v
  return s
}

func (s *ListUsersListUsersResponseContentResult) SetGroupId(v int64) *ListUsersListUsersResponseContentResult {
  s.GroupId = &v
  return s
}

func (s *ListUsersListUsersResponseContentResult) SetGroupName(v string) *ListUsersListUsersResponseContentResult {
  s.GroupName = &v
  return s
}

func (s *ListUsersListUsersResponseContentResult) SetBandwidth(v string) *ListUsersListUsersResponseContentResult {
  s.Bandwidth = &v
  return s
}

func (s *ListUsersListUsersResponseContentResult) SetRemark(v string) *ListUsersListUsersResponseContentResult {
  s.Remark = &v
  return s
}

func (s *ListUsersListUsersResponseContentResult) SetExpireTime(v int64) *ListUsersListUsersResponseContentResult {
  s.ExpireTime = &v
  return s
}

func (s *ListUsersListUsersResponseContentResult) SetEnableStatus(v int) *ListUsersListUsersResponseContentResult {
  s.EnableStatus = &v
  return s
}

func (s *ListUsersListUsersResponseContentResult) SetSmsAuth(v int) *ListUsersListUsersResponseContentResult {
  s.SmsAuth = &v
  return s
}

func (s *ListUsersListUsersResponseContentResult) SetTotpAuth(v int) *ListUsersListUsersResponseContentResult {
  s.TotpAuth = &v
  return s
}

func (s *ListUsersListUsersResponseContentResult) SetVip(v string) *ListUsersListUsersResponseContentResult {
  s.Vip = &v
  return s
}

func (s *ListUsersListUsersResponseContentResult) SetCreateTime(v int64) *ListUsersListUsersResponseContentResult {
  s.CreateTime = &v
  return s
}

type ListUsersPaths struct {
}

func (s ListUsersPaths) String() string {
  return tea.Prettify(s)
}

func (s ListUsersPaths) GoString() string {
  return s.String()
}

type ListUsersParameters struct {
  // {'en':'Query all users under the specified parent group
  // If the value is null, query all users under the root directory group.', 'zh_CN':'查询指定父组下的所有用户
  // 不填写时，查全部'}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty" require:"true"`
  // {'en':'Page number of users list
  // Start value: 1
  // Default value: 1', 'zh_CN':'用户列表的页码
  // 起始值：1
  // 默认值：1'}
  PageNo *int `json:"pageNo,omitempty" xml:"pageNo,omitempty"`
  // {'en':'The number of rows per page set during pagination query. Value range: 1~50
  // Default value: 20', 'zh_CN':'分页查询时设置的每页行数。取值范围：1~50
  // 默认值：20'}
  PageSize *int `json:"pageSize,omitempty" xml:"pageSize,omitempty"`
}

func (s ListUsersParameters) String() string {
  return tea.Prettify(s)
}

func (s ListUsersParameters) GoString() string {
  return s.String()
}

func (s *ListUsersParameters) SetGroupName(v string) *ListUsersParameters {
  s.GroupName = &v
  return s
}

func (s *ListUsersParameters) SetPageNo(v int) *ListUsersParameters {
  s.PageNo = &v
  return s
}

func (s *ListUsersParameters) SetPageSize(v int) *ListUsersParameters {
  s.PageSize = &v
  return s
}

type ListUsersRequestHeader struct {
}

func (s ListUsersRequestHeader) String() string {
  return tea.Prettify(s)
}

func (s ListUsersRequestHeader) GoString() string {
  return s.String()
}

type ListUsersResponseHeader struct {
}

func (s ListUsersResponseHeader) String() string {
  return tea.Prettify(s)
}

func (s ListUsersResponseHeader) GoString() string {
  return s.String()
}




