package authentication

// This file is auto-generated, don't edit it. Thanks.
import (
  "github.com/alibabacloud-go/tea/tea"
)

type CreateUserRequest struct {
  // {"en":"username\n\nFormat: 2-32 characters, can contain Chinese, English, numbers and symbols @ . _ -\n\nThis parameter must be specified.","zh_CN":"用户名\n2-32个字符，支持中文、英文、数字和符号@._-\n该参数必须指定"}
  Username *string `json:"username,omitempty" xml:"username,omitempty" require:"true"`
  // {"en":"Whether to send the password to the user mobile, the default is 0\n0: Do not send\n1: send","zh_CN":"是否发送密码给用户的手机，默认0\n0：不发送\n1：发送"}
  PhoneSendPwd *int `json:"phoneSendPwd,omitempty" xml:"phoneSendPwd,omitempty"`
  // {"en":"Whether to send the password to the user&lsquo;s email, the default is 0\n0: Do not send\n1: send","zh_CN":"是否发送密码给用户的邮箱，默认0\n0：不发送\n1：发送"}
  EmailSendPwd *int `json:"emailSendPwd,omitempty" xml:"emailSendPwd,omitempty"`
  // {"en":"If the parameter is  \"\" or null, it will be randomly generated by system.\nIf the parameter is not empty, it will be the password for user.\nFormat: 8-32 characters, including at least 3 types of uppercase letters, lowercase letters, numbers and punctuation marks","zh_CN":"若传参为空或不传,则随机生成\n若传参不为空，则为预设密码\n8-32个字符，字母大写、字母小写、数字和标点符号至少包含3种"}
  Password *string `json:"password,omitempty" xml:"password,omitempty"`
  // {"en":"Parent group name.\nIf the request parameters do not contain this field or it is empty, the user will belongs the root deirectory group.","zh_CN":"父组名称\n不传或空保存在根用户组下"}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty"`
  // {"en":"Bandwidth limit.\nIf the parameters do not contains this field,it  will be 1/2 of maximum bandwidth limit.\nIf the value exceeds the maximum bandwidth,it  will be maximum bandwidth limit.","zh_CN":"带宽限制(单位：Mbps)\n不传参为 1/2{最大带宽}\n传参超过最大带宽，则为{最大带宽}"}
  Bandwidth *int64 `json:"bandwidth,omitempty" xml:"bandwidth,omitempty"`
  // {"en":"Area code\nIf the areaCode is null and when cellPhone is not null, areaCode  will be 86.","zh_CN":"区号，手机号存在但区号不存在时会默认设置86"}
  AreaCode *string `json:"areaCode,omitempty" xml:"areaCode,omitempty"`
  // {"en":"Mobile.When phoneSendPwd is equal to \"1\", this field cannnot be empty.","zh_CN":"手机号；当phoneSendPwd=1时，不为空"}
  CellPhone *string `json:"cellPhone,omitempty" xml:"cellPhone,omitempty"`
  // {"en":"Email.\nWhen emailSendPwd is equal to \"1\", this field cannnot be empty.","zh_CN":"邮箱\n当emailSendPwd=1时，不为空"}
  Email *string `json:"email,omitempty" xml:"email,omitempty"`
  // {"en":"MFA: message authentication, default 0\n\"0\": off,\n\"1\":  on","zh_CN":"双因子认证 : 短信认证，默认0\n0 关闭， 1 开启"}
  SmsAuth *int `json:"smsAuth,omitempty" xml:"smsAuth,omitempty"`
  // {"en":"MFA: totp authentication, default 0\n\"0\": off,\n\"1\":  on","zh_CN":"双因子认证 : totp认证，默认0\n0 关闭， 1 开启"}
  TotpAuth *int `json:"totpAuth,omitempty" xml:"totpAuth,omitempty"`
  // {"en":"Expiration time: pass timestamp, millisecond level\nIf the parameters do not contain the filed, it will be \"0\"\n0: never expire\n1626732871372: Set expiration time","zh_CN":"过期时间，传时间戳，毫秒级别，不传为0\n0：永不过期\n1626732871372：设置过期时间"}
  ExpireTime *int64 `json:"expireTime,omitempty" xml:"expireTime,omitempty"`
  // {"en":"Whether to enable the user, do not pass the parameter to enable\n1: enable\n0: disable","zh_CN":"是否启用用户，不传参为启用\n1:启用\n0:禁用"}
  EnableStatus *int `json:"enableStatus,omitempty" xml:"enableStatus,omitempty"`
  // {"en":"Note\nMaximum length is 255 characters.","zh_CN":"备注\n最大长度255个字符"}
  Remark *string `json:"remark,omitempty" xml:"remark,omitempty"`
  // {"en":"You can choose between parentGroupId and parentGroupName. It is recommended to pass parentGroupId first to ensure uniqueness.","zh_CN":"parentGroupId和parentGroupName二选一，推荐优先传递parentGroupId，以确保唯一性"}
  ParentGroupId *string `json:"parentGroupId,omitempty" xml:"parentGroupId,omitempty"`
}

func (s CreateUserRequest) String() string {
  return tea.Prettify(s)
}

func (s CreateUserRequest) GoString() string {
  return s.String()
}

func (s *CreateUserRequest) SetUsername(v string) *CreateUserRequest {
  s.Username = &v
  return s
}

func (s *CreateUserRequest) SetPhoneSendPwd(v int) *CreateUserRequest {
  s.PhoneSendPwd = &v
  return s
}

func (s *CreateUserRequest) SetEmailSendPwd(v int) *CreateUserRequest {
  s.EmailSendPwd = &v
  return s
}

func (s *CreateUserRequest) SetPassword(v string) *CreateUserRequest {
  s.Password = &v
  return s
}

func (s *CreateUserRequest) SetGroupName(v string) *CreateUserRequest {
  s.GroupName = &v
  return s
}

func (s *CreateUserRequest) SetBandwidth(v int64) *CreateUserRequest {
  s.Bandwidth = &v
  return s
}

func (s *CreateUserRequest) SetAreaCode(v string) *CreateUserRequest {
  s.AreaCode = &v
  return s
}

func (s *CreateUserRequest) SetCellPhone(v string) *CreateUserRequest {
  s.CellPhone = &v
  return s
}

func (s *CreateUserRequest) SetEmail(v string) *CreateUserRequest {
  s.Email = &v
  return s
}

func (s *CreateUserRequest) SetSmsAuth(v int) *CreateUserRequest {
  s.SmsAuth = &v
  return s
}

func (s *CreateUserRequest) SetTotpAuth(v int) *CreateUserRequest {
  s.TotpAuth = &v
  return s
}

func (s *CreateUserRequest) SetExpireTime(v int64) *CreateUserRequest {
  s.ExpireTime = &v
  return s
}

func (s *CreateUserRequest) SetEnableStatus(v int) *CreateUserRequest {
  s.EnableStatus = &v
  return s
}

func (s *CreateUserRequest) SetRemark(v string) *CreateUserRequest {
  s.Remark = &v
  return s
}

func (s *CreateUserRequest) SetParentGroupId(v string) *CreateUserRequest {
  s.ParentGroupId = &v
  return s
}

type CreateUserRequestHeader struct {
}

func (s CreateUserRequestHeader) String() string {
  return tea.Prettify(s)
}

func (s CreateUserRequestHeader) GoString() string {
  return s.String()
}

type CreateUserPaths struct {
}

func (s CreateUserPaths) String() string {
  return tea.Prettify(s)
}

func (s CreateUserPaths) GoString() string {
  return s.String()
}

type CreateUserParameters struct {
}

func (s CreateUserParameters) String() string {
  return tea.Prettify(s)
}

func (s CreateUserParameters) GoString() string {
  return s.String()
}

type CreateUserResponse struct {
  // {"en":"Interface error code, 0-fail,1-success","zh_CN":"接口错误码，0-代表失败，1-代表成功"}
  ReturnCode *string `json:"returnCode,omitempty" xml:"returnCode,omitempty" require:"true"`
  // {"en":"Error message","zh_CN":"错误信息"}
  ReturnMsg *string `json:"returnMsg,omitempty" xml:"returnMsg,omitempty" require:"true"`
  // {"en":"content","zh_CN":"数据，下面全是数据的内容"}
  Content *CreateUserResponseContent `json:"content,omitempty" xml:"content,omitempty" require:"true" type:"Struct"`
}

func (s CreateUserResponse) String() string {
  return tea.Prettify(s)
}

func (s CreateUserResponse) GoString() string {
  return s.String()
}

func (s *CreateUserResponse) SetReturnCode(v string) *CreateUserResponse {
  s.ReturnCode = &v
  return s
}

func (s *CreateUserResponse) SetReturnMsg(v string) *CreateUserResponse {
  s.ReturnMsg = &v
  return s
}

func (s *CreateUserResponse) SetContent(v *CreateUserResponseContent) *CreateUserResponse {
  s.Content = v
  return s
}

type CreateUserResponseContent struct {
  // {"en":"username","zh_CN":"用户名称"}
  Username *string `json:"username,omitempty" xml:"username,omitempty" require:"true"`
  // {"en":"id","zh_CN":"用户id"}
  Id *int64 `json:"id,omitempty" xml:"id,omitempty" require:"true"`
  // {"en":"email","zh_CN":"邮箱"}
  Email *string `json:"email,omitempty" xml:"email,omitempty" require:"true"`
  // {"en":"areaCode","zh_CN":"区号"}
  AreaCode *string `json:"areaCode,omitempty" xml:"areaCode,omitempty" require:"true"`
  // {"en":"cellPhone","zh_CN":"手机号"}
  CellPhone *string `json:"cellPhone,omitempty" xml:"cellPhone,omitempty" require:"true"`
  // {"en":"groupId","zh_CN":"父组ID"}
  GroupId *int64 `json:"groupId,omitempty" xml:"groupId,omitempty" require:"true"`
  // {"en":"groupName","zh_CN":"父组名称"}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty" require:"true"`
  // {"en":"bandwidth","zh_CN":"带宽"}
  Bandwidth *string `json:"bandwidth,omitempty" xml:"bandwidth,omitempty" require:"true"`
  // {"en":"remark","zh_CN":"备注"}
  Remark *string `json:"remark,omitempty" xml:"remark,omitempty" require:"true"`
  // {"en":"expirationTime","zh_CN":"过期时间戳，0-永不过期"}
  ExpirationTime *int64 `json:"expirationTime,omitempty" xml:"expirationTime,omitempty" require:"true"`
  // {"en":"enableUser","zh_CN":"启用状态"}
  EnableUser *int `json:"enableUser,omitempty" xml:"enableUser,omitempty" require:"true"`
  // {"en":"smsAuth","zh_CN":"短信认证启用"}
  SmsAuth *int `json:"smsAuth,omitempty" xml:"smsAuth,omitempty" require:"true"`
  // {"en":"totpAuth","zh_CN":"totp认证启用"}
  TotpAuth *int `json:"totpAuth,omitempty" xml:"totpAuth,omitempty" require:"true"`
  // {"en":"createTime","zh_CN":"创建时间戳"}
  CreateTime *int64 `json:"createTime,omitempty" xml:"createTime,omitempty" require:"true"`
}

func (s CreateUserResponseContent) String() string {
  return tea.Prettify(s)
}

func (s CreateUserResponseContent) GoString() string {
  return s.String()
}

func (s *CreateUserResponseContent) SetUsername(v string) *CreateUserResponseContent {
  s.Username = &v
  return s
}

func (s *CreateUserResponseContent) SetId(v int64) *CreateUserResponseContent {
  s.Id = &v
  return s
}

func (s *CreateUserResponseContent) SetEmail(v string) *CreateUserResponseContent {
  s.Email = &v
  return s
}

func (s *CreateUserResponseContent) SetAreaCode(v string) *CreateUserResponseContent {
  s.AreaCode = &v
  return s
}

func (s *CreateUserResponseContent) SetCellPhone(v string) *CreateUserResponseContent {
  s.CellPhone = &v
  return s
}

func (s *CreateUserResponseContent) SetGroupId(v int64) *CreateUserResponseContent {
  s.GroupId = &v
  return s
}

func (s *CreateUserResponseContent) SetGroupName(v string) *CreateUserResponseContent {
  s.GroupName = &v
  return s
}

func (s *CreateUserResponseContent) SetBandwidth(v string) *CreateUserResponseContent {
  s.Bandwidth = &v
  return s
}

func (s *CreateUserResponseContent) SetRemark(v string) *CreateUserResponseContent {
  s.Remark = &v
  return s
}

func (s *CreateUserResponseContent) SetExpirationTime(v int64) *CreateUserResponseContent {
  s.ExpirationTime = &v
  return s
}

func (s *CreateUserResponseContent) SetEnableUser(v int) *CreateUserResponseContent {
  s.EnableUser = &v
  return s
}

func (s *CreateUserResponseContent) SetSmsAuth(v int) *CreateUserResponseContent {
  s.SmsAuth = &v
  return s
}

func (s *CreateUserResponseContent) SetTotpAuth(v int) *CreateUserResponseContent {
  s.TotpAuth = &v
  return s
}

func (s *CreateUserResponseContent) SetCreateTime(v int64) *CreateUserResponseContent {
  s.CreateTime = &v
  return s
}

type CreateUserResponseHeader struct {
}

func (s CreateUserResponseHeader) String() string {
  return tea.Prettify(s)
}

func (s CreateUserResponseHeader) GoString() string {
  return s.String()
}




type ResetUserPasswordRequest struct {
  // {"en":"Username of the specific user.","zh_CN":"需要重置密码的用户"}
  Username *string `json:"username,omitempty" xml:"username,omitempty" require:"true"`
  // {"defaultValue":"0","en":"- Password reset method, default is 0.\n- 0: Password is randomly generated. When this field is 0, the password field can be empty (\"\") or omitted. If the password field is not empty, its value is ignored, and the reset password is still randomly generated.\n- 1: Preset password. When this field is 1, the password field must be provided and cannot be empty.","zh_CN":"- 密码重置方式，默认为0\n- 0：密码随机生成。当该字段为0时，password字段允许为\"\"或不传，如果password字段不为空，则值无效，重置的密码仍为随机生成密码\n- 1：预设密码。当该字段为1时，password字段需要传参且不为空"}
  PasswordType *int `json:"passwordType,omitempty" xml:"passwordType,omitempty"`
  // {"en":"- If the parameter is an empty string (\"\") or not provided, a random password will be generated. \n- For randomly generated passwords, you must choose to receive it via email or phone, thus sendPwdType cannot include 0 and must include 1 or 2.\n- If the parameter is not empty, it is considered a preset password. The password must be 8-32 characters long and contain at least three of the following: uppercase letters, lowercase letters, numbers, and punctuation marks.","zh_CN":"- 若传参为“”或不传，则随机生成\n	- 随机生成密码必须选择使用邮箱或手机来接收，因此sendPwdType不能包含0且必须包含1或2\n- 若传参不为空，则为预设密码\n	- 8-32个字符，字母大写、字母小写、数字和标点符号至少包含3种"}
  Password *string `json:"password,omitempty" xml:"password,omitempty"`
  // {"defaultValue":"0","en":"- Force user to change password after logging in, default is 0.\n- 0: Do not force change\n- 1: Force change","zh_CN":"- 用户登录后强制重新修改密码，默认为0\n- 0：不强制修改\n- 1：强制修改"}
  ForceUpdatePwd *int `json:"forceUpdatePwd,omitempty" xml:"forceUpdatePwd,omitempty"`
  // {"defaultValue":"0","en":"- Methods for sending the password to the user, default is \"0\".\n- Pass in the desired methods of sending, multiple methods separated by commas, e.g., \"1,2\".\n	- 0: Do not send\n	- 1: Send via SMS\n	- 2: Send via email\n- Note: If the input includes 0, for example \"0,1,2\", it is considered as not to send.","zh_CN":"- 发送密码给用户的方式，默认\"0\"\n- 传入需要发送的方式，多种方式以英文逗号 , 分隔 例如：\"1,2\"\n	- 0：不发送\n	- 1：短信方式发送\n	- 2：邮箱方式发送\n- 注意：如果传入包含0，例如\"0,1,2\",则认为不发送"}
  SendPwdType *string `json:"sendPwdType,omitempty" xml:"sendPwdType,omitempty"`
  // {"en":"- Area Code\n- If the user has already set an area code and phone number, then when sendPwdType includes 1, this can be left empty or not provided. In this case, the password will be sent using the user's already set area code and phone number.\n- If the user has not set an area code and phone number, then when sendPwdType includes 1, these must be provided and cannot be empty. In this case, the provided area code and phone number will be used to send the password.\n- Note: When areaCode and cellPhone are provided, the reset password will also update the user's area code and phone number.","zh_CN":"- 区号\n- 若用户当前已设置区号和手机号，则当sendPwdType包含1时，可不传或为空。此时使用用户已设置的区号和手机号发送。\n- 若用户当前没有设置区号和手机号，则当sendPwdType包含1时，不为空。此时使用传入的区号和手机号发送。\n- 注意：当传入areaCode和cellPhone时，重置密码会同时更新用户的区号和手机号。"}
  AreaCode *string `json:"areaCode,omitempty" xml:"areaCode,omitempty"`
  // {"en":"- Phone Number\n- If the user has already set an area code and phone number, then when sendPwdType includes 1, these can be left empty or not provided. In this case, the password will be sent using the user's already set area code and phone number.\n- If the user has not set an area code and phone number, then when sendPwdType includes 1, these must be provided and cannot be empty. In this case, the provided area code and phone number will be used to send the password.\n- Note: When areaCode and cellPhone are provided, the reset process will also update the user's area code and phone number.","zh_CN":"- 手机号\n- 若用户当前已设置区号和手机号，则当sendPwdType包含1时，可不传或为空。此时使用用户已设置的区号和手机号发送。\n- 若用户当前没有设置区号和手机号，则当sendPwdType包含1时，不为空。此时使用传入的区号和手机号发送。\n- 注意：当传入areaCode和cellPhone时，重置密码会同时更新用户的区号和手机号。"}
  CellPhone *string `json:"cellPhone,omitempty" xml:"cellPhone,omitempty"`
  // {"en":"- Email\n- If the user has already set an email, then when sendPwdType includes 2, this can be left empty or not provided. In this case, the password will be sent using the user's already set email.\n- If the user has not set an email, then when sendPwdType includes 2, it must be provided and cannot be empty. In this case, the provided email will be used to send the password.\n- Note: When email is provided, the reset process will also update the user's email.","zh_CN":"- 邮箱\n- 若用户当前已设置邮箱，则当sendPwdType包含2时，可不传或为空。此时使用用户已设置的邮箱发送。\n- 若用户当前没有设置邮箱，则当sendPwdType包含2时，不为空。此时使用传入的邮箱发送。\n- 注意：当传入email时，重置密码会同时更新用户的邮箱。"}
  Email *string `json:"email,omitempty" xml:"email,omitempty"`
  // {"defaultValue":"1","en":"- Language for sending password via SMS to the user, default is 1.\n- 1: Chinese\n- 2: English","zh_CN":"- 短信发送密码给用户的语言，默认1\n- 1：中文\n- 2：英文"}
  SmsLanguage *int `json:"smsLanguage,omitempty" xml:"smsLanguage,omitempty"`
}

func (s ResetUserPasswordRequest) String() string {
  return tea.Prettify(s)
}

func (s ResetUserPasswordRequest) GoString() string {
  return s.String()
}

func (s *ResetUserPasswordRequest) SetUsername(v string) *ResetUserPasswordRequest {
  s.Username = &v
  return s
}

func (s *ResetUserPasswordRequest) SetPasswordType(v int) *ResetUserPasswordRequest {
  s.PasswordType = &v
  return s
}

func (s *ResetUserPasswordRequest) SetPassword(v string) *ResetUserPasswordRequest {
  s.Password = &v
  return s
}

func (s *ResetUserPasswordRequest) SetForceUpdatePwd(v int) *ResetUserPasswordRequest {
  s.ForceUpdatePwd = &v
  return s
}

func (s *ResetUserPasswordRequest) SetSendPwdType(v string) *ResetUserPasswordRequest {
  s.SendPwdType = &v
  return s
}

func (s *ResetUserPasswordRequest) SetAreaCode(v string) *ResetUserPasswordRequest {
  s.AreaCode = &v
  return s
}

func (s *ResetUserPasswordRequest) SetCellPhone(v string) *ResetUserPasswordRequest {
  s.CellPhone = &v
  return s
}

func (s *ResetUserPasswordRequest) SetEmail(v string) *ResetUserPasswordRequest {
  s.Email = &v
  return s
}

func (s *ResetUserPasswordRequest) SetSmsLanguage(v int) *ResetUserPasswordRequest {
  s.SmsLanguage = &v
  return s
}

type ResetUserPasswordRequestHeader struct {
}

func (s ResetUserPasswordRequestHeader) String() string {
  return tea.Prettify(s)
}

func (s ResetUserPasswordRequestHeader) GoString() string {
  return s.String()
}

type ResetUserPasswordPaths struct {
}

func (s ResetUserPasswordPaths) String() string {
  return tea.Prettify(s)
}

func (s ResetUserPasswordPaths) GoString() string {
  return s.String()
}

type ResetUserPasswordParameters struct {
}

func (s ResetUserPasswordParameters) String() string {
  return tea.Prettify(s)
}

func (s ResetUserPasswordParameters) GoString() string {
  return s.String()
}

type ResetUserPasswordResponse struct {
  // {"en":"Interface error code,0-fail,1-success","zh_CN":"接口错误码，0-代表失败，1-代表成功"}
  ReturnCode *string `json:"returnCode,omitempty" xml:"returnCode,omitempty" require:"true"`
  // {"en":"Error message","zh_CN":"错误信息"}
  ReturnMsg *string `json:"returnMsg,omitempty" xml:"returnMsg,omitempty" require:"true"`
}

func (s ResetUserPasswordResponse) String() string {
  return tea.Prettify(s)
}

func (s ResetUserPasswordResponse) GoString() string {
  return s.String()
}

func (s *ResetUserPasswordResponse) SetReturnCode(v string) *ResetUserPasswordResponse {
  s.ReturnCode = &v
  return s
}

func (s *ResetUserPasswordResponse) SetReturnMsg(v string) *ResetUserPasswordResponse {
  s.ReturnMsg = &v
  return s
}

type ResetUserPasswordResponseHeader struct {
}

func (s ResetUserPasswordResponseHeader) String() string {
  return tea.Prettify(s)
}

func (s ResetUserPasswordResponseHeader) GoString() string {
  return s.String()
}




type ModifyGroupRequest struct {
  // {"en":"User group name\nThis parameter must be specified.","zh_CN":"用户组名称"}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty" require:"true"`
  // {"en":"new Group name.\nThe maximum length is 32 characters, and it can be the combination of English, Chinese, and numbers. It cannot contain /","zh_CN":"用户组名称\n最大长度32个字符，支持英文、中文、数字的组合，不可包含/\n该参数必须指定"}
  NewGroupName *string `json:"newGroupName,omitempty" xml:"newGroupName,omitempty"`
  // {"en":"none","zh_CN":"{'en':'new Parent group name.\nIf the value is '', the group will belongs the root deirectory group.', 'zh_CN':'若传参为&ldquo;&rdquo;，则在根目录下'}"}
  NewParentGroupName *string `json:"newParentGroupName,omitempty" xml:"newParentGroupName,omitempty"`
  // {"en":"New note\nMaximum length is 255 characters.","zh_CN":"新的备注\n最大长度255个字符\n不传不修改"}
  Remark *string `json:"remark,omitempty" xml:"remark,omitempty"`
  // {"en":"You can choose between parentGroupId and parentGroupName. It is recommended to pass parentGroupId first to ensure uniqueness.","zh_CN":"parentGroupId和parentGroupName二选一，推荐优先传递parentGroupId，以确保唯一性"}
  ParentGroupId *string `json:"parentGroupId,omitempty" xml:"parentGroupId,omitempty"`
  // {"en":"Choose between newParentGroupId and newParentGroupName. It is recommended to pass newParentGroupId first to ensure uniqueness.","zh_CN":"newParentGroupId和newParentGroupName二选一，推荐优先传递newParentGroupId，以确保唯一性"}
  NewParentGroupId *string `json:"newParentGroupId,omitempty" xml:"newParentGroupId,omitempty"`
}

func (s ModifyGroupRequest) String() string {
  return tea.Prettify(s)
}

func (s ModifyGroupRequest) GoString() string {
  return s.String()
}

func (s *ModifyGroupRequest) SetGroupName(v string) *ModifyGroupRequest {
  s.GroupName = &v
  return s
}

func (s *ModifyGroupRequest) SetNewGroupName(v string) *ModifyGroupRequest {
  s.NewGroupName = &v
  return s
}

func (s *ModifyGroupRequest) SetNewParentGroupName(v string) *ModifyGroupRequest {
  s.NewParentGroupName = &v
  return s
}

func (s *ModifyGroupRequest) SetRemark(v string) *ModifyGroupRequest {
  s.Remark = &v
  return s
}

func (s *ModifyGroupRequest) SetParentGroupId(v string) *ModifyGroupRequest {
  s.ParentGroupId = &v
  return s
}

func (s *ModifyGroupRequest) SetNewParentGroupId(v string) *ModifyGroupRequest {
  s.NewParentGroupId = &v
  return s
}

type ModifyGroupRequestHeader struct {
}

func (s ModifyGroupRequestHeader) String() string {
  return tea.Prettify(s)
}

func (s ModifyGroupRequestHeader) GoString() string {
  return s.String()
}

type ModifyGroupPaths struct {
}

func (s ModifyGroupPaths) String() string {
  return tea.Prettify(s)
}

func (s ModifyGroupPaths) GoString() string {
  return s.String()
}

type ModifyGroupParameters struct {
}

func (s ModifyGroupParameters) String() string {
  return tea.Prettify(s)
}

func (s ModifyGroupParameters) GoString() string {
  return s.String()
}

type ModifyGroupResponse struct {
  // {"en":"none","zh_CN":"{'en':'Interface error code, '1' means success', 'zh_CN':'接口错误码，&ldquo;1&rdquo;代表成功'}"}
  ReturnCode *string `json:"returnCode,omitempty" xml:"returnCode,omitempty" require:"true"`
  // {"en":"Error message","zh_CN":"错误信息"}
  ReturnMsg *string `json:"returnMsg,omitempty" xml:"returnMsg,omitempty" require:"true"`
  // {"en":"content","zh_CN":"数据，下面全是数据的内容"}
  Content *ModifyGroupResponseContent `json:"content,omitempty" xml:"content,omitempty" require:"true" type:"Struct"`
}

func (s ModifyGroupResponse) String() string {
  return tea.Prettify(s)
}

func (s ModifyGroupResponse) GoString() string {
  return s.String()
}

func (s *ModifyGroupResponse) SetReturnCode(v string) *ModifyGroupResponse {
  s.ReturnCode = &v
  return s
}

func (s *ModifyGroupResponse) SetReturnMsg(v string) *ModifyGroupResponse {
  s.ReturnMsg = &v
  return s
}

func (s *ModifyGroupResponse) SetContent(v *ModifyGroupResponseContent) *ModifyGroupResponse {
  s.Content = v
  return s
}

type ModifyGroupResponseContent struct {
  // {"en":"groupName","zh_CN":"用户组名称"}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty" require:"true"`
  // {"en":"groupId","zh_CN":"用户组ID"}
  GroupId *int64 `json:"groupId,omitempty" xml:"groupId,omitempty" require:"true"`
  // {"en":"parentGroupName","zh_CN":"父组名称"}
  ParentGroupName *string `json:"parentGroupName,omitempty" xml:"parentGroupName,omitempty" require:"true"`
  // {"en":"parentGroupID","zh_CN":"父组ID"}
  ParentGroupId *string `json:"parentGroupId,omitempty" xml:"parentGroupId,omitempty" require:"true"`
  // {"en":"remark","zh_CN":"备注"}
  Remark *string `json:"remark,omitempty" xml:"remark,omitempty" require:"true"`
  // {"en":"createTime","zh_CN":"创建时间"}
  CreateTime *int64 `json:"createTime,omitempty" xml:"createTime,omitempty" require:"true"`
  // {"en":"updateTime","zh_CN":"更新时间"}
  UpdateTime *int64 `json:"updateTime,omitempty" xml:"updateTime,omitempty" require:"true"`
}

func (s ModifyGroupResponseContent) String() string {
  return tea.Prettify(s)
}

func (s ModifyGroupResponseContent) GoString() string {
  return s.String()
}

func (s *ModifyGroupResponseContent) SetGroupName(v string) *ModifyGroupResponseContent {
  s.GroupName = &v
  return s
}

func (s *ModifyGroupResponseContent) SetGroupId(v int64) *ModifyGroupResponseContent {
  s.GroupId = &v
  return s
}

func (s *ModifyGroupResponseContent) SetParentGroupName(v string) *ModifyGroupResponseContent {
  s.ParentGroupName = &v
  return s
}

func (s *ModifyGroupResponseContent) SetParentGroupId(v string) *ModifyGroupResponseContent {
  s.ParentGroupId = &v
  return s
}

func (s *ModifyGroupResponseContent) SetRemark(v string) *ModifyGroupResponseContent {
  s.Remark = &v
  return s
}

func (s *ModifyGroupResponseContent) SetCreateTime(v int64) *ModifyGroupResponseContent {
  s.CreateTime = &v
  return s
}

func (s *ModifyGroupResponseContent) SetUpdateTime(v int64) *ModifyGroupResponseContent {
  s.UpdateTime = &v
  return s
}

type ModifyGroupResponseHeader struct {
}

func (s ModifyGroupResponseHeader) String() string {
  return tea.Prettify(s)
}

func (s ModifyGroupResponseHeader) GoString() string {
  return s.String()
}




type CreateGroupRequest struct {
  // {"en":"Group name.\nThe maximum length is 32 characters, and it can be the combination of English, Chinese, and numbers. It cannot contain /\nThis parameter must be specified.","zh_CN":"用户组名称\n最大长度32个字符，支持英文、中文、数字的组合，不可包含/\n该参数必须指定"}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty" require:"true"`
  // {"en":"Parent group name.\nIf the request parameters do not contain this field or it is empty, the group will belongs the root deirectory group.","zh_CN":"若传参为空或不传，则在根目录下"}
  ParentGroupName *string `json:"parentGroupName,omitempty" xml:"parentGroupName,omitempty"`
  // {"en":"Note\nMaximum length is 255 characters.","zh_CN":"新的备注\n最大长度255个字符"}
  Remark *string `json:"remark,omitempty" xml:"remark,omitempty"`
  // {"en":"You can choose between parentGroupId and parentGroupName. It is recommended to pass parentGroupId first to ensure uniqueness.","zh_CN":"parentGroupId和parentGroupName二选一，推荐优先传递parentGroupId，以确保唯一性"}
  ParentGroupId *string `json:"parentGroupId,omitempty" xml:"parentGroupId,omitempty"`
}

func (s CreateGroupRequest) String() string {
  return tea.Prettify(s)
}

func (s CreateGroupRequest) GoString() string {
  return s.String()
}

func (s *CreateGroupRequest) SetGroupName(v string) *CreateGroupRequest {
  s.GroupName = &v
  return s
}

func (s *CreateGroupRequest) SetParentGroupName(v string) *CreateGroupRequest {
  s.ParentGroupName = &v
  return s
}

func (s *CreateGroupRequest) SetRemark(v string) *CreateGroupRequest {
  s.Remark = &v
  return s
}

func (s *CreateGroupRequest) SetParentGroupId(v string) *CreateGroupRequest {
  s.ParentGroupId = &v
  return s
}

type CreateGroupRequestHeader struct {
}

func (s CreateGroupRequestHeader) String() string {
  return tea.Prettify(s)
}

func (s CreateGroupRequestHeader) GoString() string {
  return s.String()
}

type CreateGroupPaths struct {
}

func (s CreateGroupPaths) String() string {
  return tea.Prettify(s)
}

func (s CreateGroupPaths) GoString() string {
  return s.String()
}

type CreateGroupParameters struct {
}

func (s CreateGroupParameters) String() string {
  return tea.Prettify(s)
}

func (s CreateGroupParameters) GoString() string {
  return s.String()
}

type CreateGroupResponse struct {
  // {"en":"Interface error code, 0-fail,1-success","zh_CN":"接口错误码，0-代表失败，1-代表成功"}
  ReturnCode *string `json:"returnCode,omitempty" xml:"returnCode,omitempty" require:"true"`
  // {"en":"Error message","zh_CN":"错误信息"}
  ReturnMsg *string `json:"returnMsg,omitempty" xml:"returnMsg,omitempty" require:"true"`
  // {"en":"content","zh_CN":"数据，下面全是数据的内容"}
  Content *CreateGroupResponseContent `json:"content,omitempty" xml:"content,omitempty" require:"true" type:"Struct"`
}

func (s CreateGroupResponse) String() string {
  return tea.Prettify(s)
}

func (s CreateGroupResponse) GoString() string {
  return s.String()
}

func (s *CreateGroupResponse) SetReturnCode(v string) *CreateGroupResponse {
  s.ReturnCode = &v
  return s
}

func (s *CreateGroupResponse) SetReturnMsg(v string) *CreateGroupResponse {
  s.ReturnMsg = &v
  return s
}

func (s *CreateGroupResponse) SetContent(v *CreateGroupResponseContent) *CreateGroupResponse {
  s.Content = v
  return s
}

type CreateGroupResponseContent struct {
  // {"en":"groupName","zh_CN":"用户组名称"}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty" require:"true"`
  // {"en":"groupId","zh_CN":"用户组ID"}
  GroupId *int64 `json:"groupId,omitempty" xml:"groupId,omitempty" require:"true"`
  // {"en":"parentGroupName","zh_CN":"父组名称"}
  ParentGroupName *string `json:"parentGroupName,omitempty" xml:"parentGroupName,omitempty" require:"true"`
  // {"en":"parentGroupID","zh_CN":"父组ID"}
  ParentGroupId *string `json:"parentGroupId,omitempty" xml:"parentGroupId,omitempty" require:"true"`
  // {"en":"remark","zh_CN":"备注"}
  Remark *string `json:"remark,omitempty" xml:"remark,omitempty" require:"true"`
  // {"en":"createTime","zh_CN":"创建时间"}
  CreateTime *int64 `json:"createTime,omitempty" xml:"createTime,omitempty" require:"true"`
  // {"en":"updateTime","zh_CN":"更新时间"}
  UpdateTime *int64 `json:"updateTime,omitempty" xml:"updateTime,omitempty" require:"true"`
}

func (s CreateGroupResponseContent) String() string {
  return tea.Prettify(s)
}

func (s CreateGroupResponseContent) GoString() string {
  return s.String()
}

func (s *CreateGroupResponseContent) SetGroupName(v string) *CreateGroupResponseContent {
  s.GroupName = &v
  return s
}

func (s *CreateGroupResponseContent) SetGroupId(v int64) *CreateGroupResponseContent {
  s.GroupId = &v
  return s
}

func (s *CreateGroupResponseContent) SetParentGroupName(v string) *CreateGroupResponseContent {
  s.ParentGroupName = &v
  return s
}

func (s *CreateGroupResponseContent) SetParentGroupId(v string) *CreateGroupResponseContent {
  s.ParentGroupId = &v
  return s
}

func (s *CreateGroupResponseContent) SetRemark(v string) *CreateGroupResponseContent {
  s.Remark = &v
  return s
}

func (s *CreateGroupResponseContent) SetCreateTime(v int64) *CreateGroupResponseContent {
  s.CreateTime = &v
  return s
}

func (s *CreateGroupResponseContent) SetUpdateTime(v int64) *CreateGroupResponseContent {
  s.UpdateTime = &v
  return s
}

type CreateGroupResponseHeader struct {
}

func (s CreateGroupResponseHeader) String() string {
  return tea.Prettify(s)
}

func (s CreateGroupResponseHeader) GoString() string {
  return s.String()
}




type DescribeUserInfoRequest struct {
}

func (s DescribeUserInfoRequest) String() string {
  return tea.Prettify(s)
}

func (s DescribeUserInfoRequest) GoString() string {
  return s.String()
}

type DescribeUserInfoRequestHeader struct {
}

func (s DescribeUserInfoRequestHeader) String() string {
  return tea.Prettify(s)
}

func (s DescribeUserInfoRequestHeader) GoString() string {
  return s.String()
}

type DescribeUserInfoPaths struct {
}

func (s DescribeUserInfoPaths) String() string {
  return tea.Prettify(s)
}

func (s DescribeUserInfoPaths) GoString() string {
  return s.String()
}

type DescribeUserInfoParameters struct {
  // {"en":"username","zh_CN":"用户名"}
  Username *string `json:"username,omitempty" xml:"username,omitempty" require:"true"`
}

func (s DescribeUserInfoParameters) String() string {
  return tea.Prettify(s)
}

func (s DescribeUserInfoParameters) GoString() string {
  return s.String()
}

func (s *DescribeUserInfoParameters) SetUsername(v string) *DescribeUserInfoParameters {
  s.Username = &v
  return s
}

type DescribeUserInfoResponse struct {
  // {"en":"Interface error code, 0-fail,1-success","zh_CN":"接口错误码，0-代表失败，1-代表成功"}
  ReturnCode *string `json:"returnCode,omitempty" xml:"returnCode,omitempty" require:"true"`
  // {"en":"Error message","zh_CN":"错误信息"}
  ReturnMsg *string `json:"returnMsg,omitempty" xml:"returnMsg,omitempty" require:"true"`
  // {"en":"content","zh_CN":"数据，下面全是数据的内容"}
  Content *DescribeUserInfoResponseContent `json:"content,omitempty" xml:"content,omitempty" require:"true" type:"Struct"`
}

func (s DescribeUserInfoResponse) String() string {
  return tea.Prettify(s)
}

func (s DescribeUserInfoResponse) GoString() string {
  return s.String()
}

func (s *DescribeUserInfoResponse) SetReturnCode(v string) *DescribeUserInfoResponse {
  s.ReturnCode = &v
  return s
}

func (s *DescribeUserInfoResponse) SetReturnMsg(v string) *DescribeUserInfoResponse {
  s.ReturnMsg = &v
  return s
}

func (s *DescribeUserInfoResponse) SetContent(v *DescribeUserInfoResponseContent) *DescribeUserInfoResponse {
  s.Content = v
  return s
}

type DescribeUserInfoResponseContent struct {
  // {"en":"username","zh_CN":"用户名称"}
  Username *string `json:"username,omitempty" xml:"username,omitempty" require:"true"`
  // {"en":"id","zh_CN":"用户id"}
  Id *int64 `json:"id,omitempty" xml:"id,omitempty" require:"true"`
  // {"en":"email","zh_CN":"邮箱"}
  Email *string `json:"email,omitempty" xml:"email,omitempty" require:"true"`
  // {"en":"areaCode","zh_CN":"区号"}
  AreaCode *string `json:"areaCode,omitempty" xml:"areaCode,omitempty" require:"true"`
  // {"en":"cellPhone","zh_CN":"手机号"}
  CellPhone *string `json:"cellPhone,omitempty" xml:"cellPhone,omitempty" require:"true"`
  // {"en":"groupId","zh_CN":"父组ID"}
  GroupId *int64 `json:"groupId,omitempty" xml:"groupId,omitempty" require:"true"`
  // {"en":"groupName","zh_CN":"父组名称"}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty" require:"true"`
  // {"en":"bandwidth","zh_CN":"带宽"}
  Bandwidth *string `json:"bandwidth,omitempty" xml:"bandwidth,omitempty" require:"true"`
  // {"en":"remark","zh_CN":"备注"}
  Remark *string `json:"remark,omitempty" xml:"remark,omitempty" require:"true"`
  // {"en":"expirationTime","zh_CN":"过期时间戳，0-永不过期"}
  ExpirationTime *int64 `json:"expirationTime,omitempty" xml:"expirationTime,omitempty" require:"true"`
  // {"en":"enableUser","zh_CN":"启用状态"}
  EnableUser *int `json:"enableUser,omitempty" xml:"enableUser,omitempty" require:"true"`
  // {"en":"smsAuth","zh_CN":"短信认证启用"}
  SmsAuth *int `json:"smsAuth,omitempty" xml:"smsAuth,omitempty" require:"true"`
  // {"en":"totpAuth","zh_CN":"totp认证启用"}
  TotpAuth *int `json:"totpAuth,omitempty" xml:"totpAuth,omitempty" require:"true"`
  // {"en":"virtual ip","zh_CN":"虚拟ip"}
  Vip *string `json:"vip,omitempty" xml:"vip,omitempty" require:"true"`
  // {"en":"createTime","zh_CN":"创建时间戳"}
  CreateTime *int64 `json:"createTime,omitempty" xml:"createTime,omitempty" require:"true"`
}

func (s DescribeUserInfoResponseContent) String() string {
  return tea.Prettify(s)
}

func (s DescribeUserInfoResponseContent) GoString() string {
  return s.String()
}

func (s *DescribeUserInfoResponseContent) SetUsername(v string) *DescribeUserInfoResponseContent {
  s.Username = &v
  return s
}

func (s *DescribeUserInfoResponseContent) SetId(v int64) *DescribeUserInfoResponseContent {
  s.Id = &v
  return s
}

func (s *DescribeUserInfoResponseContent) SetEmail(v string) *DescribeUserInfoResponseContent {
  s.Email = &v
  return s
}

func (s *DescribeUserInfoResponseContent) SetAreaCode(v string) *DescribeUserInfoResponseContent {
  s.AreaCode = &v
  return s
}

func (s *DescribeUserInfoResponseContent) SetCellPhone(v string) *DescribeUserInfoResponseContent {
  s.CellPhone = &v
  return s
}

func (s *DescribeUserInfoResponseContent) SetGroupId(v int64) *DescribeUserInfoResponseContent {
  s.GroupId = &v
  return s
}

func (s *DescribeUserInfoResponseContent) SetGroupName(v string) *DescribeUserInfoResponseContent {
  s.GroupName = &v
  return s
}

func (s *DescribeUserInfoResponseContent) SetBandwidth(v string) *DescribeUserInfoResponseContent {
  s.Bandwidth = &v
  return s
}

func (s *DescribeUserInfoResponseContent) SetRemark(v string) *DescribeUserInfoResponseContent {
  s.Remark = &v
  return s
}

func (s *DescribeUserInfoResponseContent) SetExpirationTime(v int64) *DescribeUserInfoResponseContent {
  s.ExpirationTime = &v
  return s
}

func (s *DescribeUserInfoResponseContent) SetEnableUser(v int) *DescribeUserInfoResponseContent {
  s.EnableUser = &v
  return s
}

func (s *DescribeUserInfoResponseContent) SetSmsAuth(v int) *DescribeUserInfoResponseContent {
  s.SmsAuth = &v
  return s
}

func (s *DescribeUserInfoResponseContent) SetTotpAuth(v int) *DescribeUserInfoResponseContent {
  s.TotpAuth = &v
  return s
}

func (s *DescribeUserInfoResponseContent) SetVip(v string) *DescribeUserInfoResponseContent {
  s.Vip = &v
  return s
}

func (s *DescribeUserInfoResponseContent) SetCreateTime(v int64) *DescribeUserInfoResponseContent {
  s.CreateTime = &v
  return s
}

type DescribeUserInfoResponseHeader struct {
}

func (s DescribeUserInfoResponseHeader) String() string {
  return tea.Prettify(s)
}

func (s DescribeUserInfoResponseHeader) GoString() string {
  return s.String()
}




type DeleteGroupRequest struct {
  // {"en":"User group name","zh_CN":"用户组名称"}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty" require:"true"`
  // {"en":"You can choose between parentGroupId and parentGroupName. It is recommended to pass parentGroupId first to ensure uniqueness.","zh_CN":"parentGroupId和parentGroupName二选一，推荐优先传递parentGroupId，以确保唯一性"}
  ParentGroupId *string `json:"parentGroupId,omitempty" xml:"parentGroupId,omitempty"`
}

func (s DeleteGroupRequest) String() string {
  return tea.Prettify(s)
}

func (s DeleteGroupRequest) GoString() string {
  return s.String()
}

func (s *DeleteGroupRequest) SetGroupName(v string) *DeleteGroupRequest {
  s.GroupName = &v
  return s
}

func (s *DeleteGroupRequest) SetParentGroupId(v string) *DeleteGroupRequest {
  s.ParentGroupId = &v
  return s
}

type DeleteGroupRequestHeader struct {
}

func (s DeleteGroupRequestHeader) String() string {
  return tea.Prettify(s)
}

func (s DeleteGroupRequestHeader) GoString() string {
  return s.String()
}

type DeleteGroupPaths struct {
}

func (s DeleteGroupPaths) String() string {
  return tea.Prettify(s)
}

func (s DeleteGroupPaths) GoString() string {
  return s.String()
}

type DeleteGroupParameters struct {
}

func (s DeleteGroupParameters) String() string {
  return tea.Prettify(s)
}

func (s DeleteGroupParameters) GoString() string {
  return s.String()
}

type DeleteGroupResponse struct {
  // {"en":"Interface error code, 0-fail,1-success","zh_CN":"接口错误码，0-代表失败，1-代表成功"}
  ReturnCode *string `json:"returnCode,omitempty" xml:"returnCode,omitempty" require:"true"`
  // {"en":"Error message","zh_CN":"错误信息"}
  ReturnMsg *string `json:"returnMsg,omitempty" xml:"returnMsg,omitempty" require:"true"`
}

func (s DeleteGroupResponse) String() string {
  return tea.Prettify(s)
}

func (s DeleteGroupResponse) GoString() string {
  return s.String()
}

func (s *DeleteGroupResponse) SetReturnCode(v string) *DeleteGroupResponse {
  s.ReturnCode = &v
  return s
}

func (s *DeleteGroupResponse) SetReturnMsg(v string) *DeleteGroupResponse {
  s.ReturnMsg = &v
  return s
}

type DeleteGroupResponseHeader struct {
}

func (s DeleteGroupResponseHeader) String() string {
  return tea.Prettify(s)
}

func (s DeleteGroupResponseHeader) GoString() string {
  return s.String()
}




type ModifyuserRequest struct {
  // {"en":"Username of the specific user.","zh_CN":"需要修改的用户"}
  Username *string `json:"username,omitempty" xml:"username,omitempty" require:"true"`
  // {"en":"Parent group name","zh_CN":"父组名称"}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty"`
  // {"en":"Area code\nIf the areaCode is null and when cellPhone is not null, areaCode  will be 86.","zh_CN":"区号，手机号存在但区号不存在时会默认设置86"}
  AreaCode *string `json:"areaCode,omitempty" xml:"areaCode,omitempty"`
  // {"en":"Mobile","zh_CN":"手机号"}
  CellPhone *string `json:"cellPhone,omitempty" xml:"cellPhone,omitempty"`
  // {"en":"MFA: message authentication, default 0\n0: off,\n1:  on","zh_CN":"双因子认证 : 短信认证，默认0\n0 关闭， 1 开启"}
  SmsAuth *int `json:"smsAuth,omitempty" xml:"smsAuth,omitempty"`
  // {"en":"MFA: totp authentication, default 0\n0: off,\n1:  on","zh_CN":"双因子认证 : totp认证，默认0\n0 关闭， 1 开启"}
  TotpAuth *int `json:"totpAuth,omitempty" xml:"totpAuth,omitempty"`
  // {"en":"Mail.","zh_CN":"邮箱"}
  Email *string `json:"email,omitempty" xml:"email,omitempty"`
  // {"en":"Expiration time, pass timestamp, millisecond level, do not pass as 0\n0: never expire\n1626732871372: Set expiration time","zh_CN":"过期时间，传时间戳，毫秒级别，不传为0\n0：永不过期\n1626732871372：设置过期时间"}
  ExpireTime *int64 `json:"expireTime,omitempty" xml:"expireTime,omitempty"`
  // {"en":"Whether to enable the user, do not pass the parameter to enable\n1: enable\n0: disable","zh_CN":"是否启用用户，不传参为启用\n1:启用\n0:禁用"}
  EnableStatus *int `json:"enableStatus,omitempty" xml:"enableStatus,omitempty"`
  // {"en":"New note\nMaximum length is 255 characters.","zh_CN":"新的备注\n最大长度255个字符"}
  Remark *string `json:"remark,omitempty" xml:"remark,omitempty"`
  // {"en":"Bandwidth limit\nNo parameter transmission is 1/2{max bandwidth}\nIf the parameter transmission exceeds the maximum bandwidth, it is {maximum bandwidth}","zh_CN":"带宽限制\n不传参为 1/2{最大带宽}\n传参超过最大带宽，则为{最大带宽}"}
  Bandwidth *ModifyuserRequestBandwidth `json:"bandwidth,omitempty" xml:"bandwidth,omitempty" type:"Struct"`
  // {"en":"You can choose between parentGroupId and parentGroupName. It is recommended to pass parentGroupId first to ensure uniqueness.","zh_CN":"parentGroupId和parentGroupName二选一，推荐优先传递parentGroupId，以确保唯一性"}
  ParentGroupId *string `json:"parentGroupId,omitempty" xml:"parentGroupId,omitempty"`
}

func (s ModifyuserRequest) String() string {
  return tea.Prettify(s)
}

func (s ModifyuserRequest) GoString() string {
  return s.String()
}

func (s *ModifyuserRequest) SetUsername(v string) *ModifyuserRequest {
  s.Username = &v
  return s
}

func (s *ModifyuserRequest) SetGroupName(v string) *ModifyuserRequest {
  s.GroupName = &v
  return s
}

func (s *ModifyuserRequest) SetAreaCode(v string) *ModifyuserRequest {
  s.AreaCode = &v
  return s
}

func (s *ModifyuserRequest) SetCellPhone(v string) *ModifyuserRequest {
  s.CellPhone = &v
  return s
}

func (s *ModifyuserRequest) SetSmsAuth(v int) *ModifyuserRequest {
  s.SmsAuth = &v
  return s
}

func (s *ModifyuserRequest) SetTotpAuth(v int) *ModifyuserRequest {
  s.TotpAuth = &v
  return s
}

func (s *ModifyuserRequest) SetEmail(v string) *ModifyuserRequest {
  s.Email = &v
  return s
}

func (s *ModifyuserRequest) SetExpireTime(v int64) *ModifyuserRequest {
  s.ExpireTime = &v
  return s
}

func (s *ModifyuserRequest) SetEnableStatus(v int) *ModifyuserRequest {
  s.EnableStatus = &v
  return s
}

func (s *ModifyuserRequest) SetRemark(v string) *ModifyuserRequest {
  s.Remark = &v
  return s
}

func (s *ModifyuserRequest) SetBandwidth(v *ModifyuserRequestBandwidth) *ModifyuserRequest {
  s.Bandwidth = v
  return s
}

func (s *ModifyuserRequest) SetParentGroupId(v string) *ModifyuserRequest {
  s.ParentGroupId = &v
  return s
}

type ModifyuserRequestBandwidth struct {
}

func (s ModifyuserRequestBandwidth) String() string {
  return tea.Prettify(s)
}

func (s ModifyuserRequestBandwidth) GoString() string {
  return s.String()
}

type ModifyuserRequestHeader struct {
}

func (s ModifyuserRequestHeader) String() string {
  return tea.Prettify(s)
}

func (s ModifyuserRequestHeader) GoString() string {
  return s.String()
}

type ModifyuserPaths struct {
}

func (s ModifyuserPaths) String() string {
  return tea.Prettify(s)
}

func (s ModifyuserPaths) GoString() string {
  return s.String()
}

type ModifyuserParameters struct {
}

func (s ModifyuserParameters) String() string {
  return tea.Prettify(s)
}

func (s ModifyuserParameters) GoString() string {
  return s.String()
}

type ModifyuserResponse struct {
  // {"en":"Interface error code, 0-fail,1-success","zh_CN":"接口错误码，0-代表失败，1-代表成功"}
  ReturnCode *string `json:"returnCode,omitempty" xml:"returnCode,omitempty" require:"true"`
  // {"en":"Error message","zh_CN":"错误信息"}
  ReturnMsg *string `json:"returnMsg,omitempty" xml:"returnMsg,omitempty" require:"true"`
  // {"en":"content","zh_CN":"数据，下面全是数据的内容"}
  Content *ModifyuserResponseContent `json:"content,omitempty" xml:"content,omitempty" require:"true" type:"Struct"`
}

func (s ModifyuserResponse) String() string {
  return tea.Prettify(s)
}

func (s ModifyuserResponse) GoString() string {
  return s.String()
}

func (s *ModifyuserResponse) SetReturnCode(v string) *ModifyuserResponse {
  s.ReturnCode = &v
  return s
}

func (s *ModifyuserResponse) SetReturnMsg(v string) *ModifyuserResponse {
  s.ReturnMsg = &v
  return s
}

func (s *ModifyuserResponse) SetContent(v *ModifyuserResponseContent) *ModifyuserResponse {
  s.Content = v
  return s
}

type ModifyuserResponseContent struct {
  // {"en":"username","zh_CN":"用户名称"}
  Username *string `json:"username,omitempty" xml:"username,omitempty" require:"true"`
  // {"en":"id","zh_CN":"用户id"}
  Id *int64 `json:"id,omitempty" xml:"id,omitempty" require:"true"`
  // {"en":"email","zh_CN":"邮箱"}
  Email *string `json:"email,omitempty" xml:"email,omitempty" require:"true"`
  // {"en":"areaCode","zh_CN":"区号"}
  AreaCode *string `json:"areaCode,omitempty" xml:"areaCode,omitempty" require:"true"`
  // {"en":"cellPhone","zh_CN":"手机号"}
  CellPhone *string `json:"cellPhone,omitempty" xml:"cellPhone,omitempty" require:"true"`
  // {"en":"groupId","zh_CN":"父组Id"}
  GroupId *int64 `json:"groupId,omitempty" xml:"groupId,omitempty" require:"true"`
  // {"en":"groupName","zh_CN":"父组名称"}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty" require:"true"`
  // {"en":"bandwidth","zh_CN":"带宽"}
  Bandwidth *string `json:"bandwidth,omitempty" xml:"bandwidth,omitempty" require:"true"`
  // {"en":"remark","zh_CN":"备注"}
  Remark *string `json:"remark,omitempty" xml:"remark,omitempty" require:"true"`
  // {"en":"expirationTime","zh_CN":"过期时间戳，0-永不过期"}
  ExpirationTime *int64 `json:"expirationTime,omitempty" xml:"expirationTime,omitempty" require:"true"`
  // {"en":"enableUser","zh_CN":"启用状态"}
  EnableUser *int `json:"enableUser,omitempty" xml:"enableUser,omitempty" require:"true"`
  // {"en":"smsAuth","zh_CN":"短信认证启用"}
  SmsAuth *int `json:"smsAuth,omitempty" xml:"smsAuth,omitempty" require:"true"`
  // {"en":"totpAuth","zh_CN":"totp认证启用"}
  TotpAuth *int `json:"totpAuth,omitempty" xml:"totpAuth,omitempty" require:"true"`
  // {"en":"createTime","zh_CN":"创建时间戳"}
  CreateTime *int64 `json:"createTime,omitempty" xml:"createTime,omitempty" require:"true"`
}

func (s ModifyuserResponseContent) String() string {
  return tea.Prettify(s)
}

func (s ModifyuserResponseContent) GoString() string {
  return s.String()
}

func (s *ModifyuserResponseContent) SetUsername(v string) *ModifyuserResponseContent {
  s.Username = &v
  return s
}

func (s *ModifyuserResponseContent) SetId(v int64) *ModifyuserResponseContent {
  s.Id = &v
  return s
}

func (s *ModifyuserResponseContent) SetEmail(v string) *ModifyuserResponseContent {
  s.Email = &v
  return s
}

func (s *ModifyuserResponseContent) SetAreaCode(v string) *ModifyuserResponseContent {
  s.AreaCode = &v
  return s
}

func (s *ModifyuserResponseContent) SetCellPhone(v string) *ModifyuserResponseContent {
  s.CellPhone = &v
  return s
}

func (s *ModifyuserResponseContent) SetGroupId(v int64) *ModifyuserResponseContent {
  s.GroupId = &v
  return s
}

func (s *ModifyuserResponseContent) SetGroupName(v string) *ModifyuserResponseContent {
  s.GroupName = &v
  return s
}

func (s *ModifyuserResponseContent) SetBandwidth(v string) *ModifyuserResponseContent {
  s.Bandwidth = &v
  return s
}

func (s *ModifyuserResponseContent) SetRemark(v string) *ModifyuserResponseContent {
  s.Remark = &v
  return s
}

func (s *ModifyuserResponseContent) SetExpirationTime(v int64) *ModifyuserResponseContent {
  s.ExpirationTime = &v
  return s
}

func (s *ModifyuserResponseContent) SetEnableUser(v int) *ModifyuserResponseContent {
  s.EnableUser = &v
  return s
}

func (s *ModifyuserResponseContent) SetSmsAuth(v int) *ModifyuserResponseContent {
  s.SmsAuth = &v
  return s
}

func (s *ModifyuserResponseContent) SetTotpAuth(v int) *ModifyuserResponseContent {
  s.TotpAuth = &v
  return s
}

func (s *ModifyuserResponseContent) SetCreateTime(v int64) *ModifyuserResponseContent {
  s.CreateTime = &v
  return s
}

type ModifyuserResponseHeader struct {
}

func (s ModifyuserResponseHeader) String() string {
  return tea.Prettify(s)
}

func (s ModifyuserResponseHeader) GoString() string {
  return s.String()
}




type SyncAuthConfigRequest struct {
  // {"en":"auth config name", "zh_CN":"身份源名称"}
  AuthConfigName *string `json:"authConfigName,omitempty" xml:"authConfigName,omitempty" require:"true"`
}

func (s SyncAuthConfigRequest) String() string {
  return tea.Prettify(s)
}

func (s SyncAuthConfigRequest) GoString() string {
  return s.String()
}

func (s *SyncAuthConfigRequest) SetAuthConfigName(v string) *SyncAuthConfigRequest {
  s.AuthConfigName = &v
  return s
}

type SyncAuthConfigResponse struct {
  // {"en":"Interface error code, 0-fail,1-success", "zh_CN":"接口错误码，0-代表失败，1-代表成功"}
  ReturnCode *string `json:"returnCode,omitempty" xml:"returnCode,omitempty" require:"true"`
  // {"en":"Error message", "zh_CN":"错误信息"}
  ReturnMsg *string `json:"returnMsg,omitempty" xml:"returnMsg,omitempty" require:"true"`
}

func (s SyncAuthConfigResponse) String() string {
  return tea.Prettify(s)
}

func (s SyncAuthConfigResponse) GoString() string {
  return s.String()
}

func (s *SyncAuthConfigResponse) SetReturnCode(v string) *SyncAuthConfigResponse {
  s.ReturnCode = &v
  return s
}

func (s *SyncAuthConfigResponse) SetReturnMsg(v string) *SyncAuthConfigResponse {
  s.ReturnMsg = &v
  return s
}

type SyncAuthConfigPaths struct {
}

func (s SyncAuthConfigPaths) String() string {
  return tea.Prettify(s)
}

func (s SyncAuthConfigPaths) GoString() string {
  return s.String()
}

type SyncAuthConfigParameters struct {
}

func (s SyncAuthConfigParameters) String() string {
  return tea.Prettify(s)
}

func (s SyncAuthConfigParameters) GoString() string {
  return s.String()
}

type SyncAuthConfigRequestHeader struct {
  // {"en":"uac account name", "zh_CN":"当前企业的UAC主账号名"}
  AuthUser *string `json:"authUser,omitempty" xml:"authUser,omitempty" require:"true"`
}

func (s SyncAuthConfigRequestHeader) String() string {
  return tea.Prettify(s)
}

func (s SyncAuthConfigRequestHeader) GoString() string {
  return s.String()
}

func (s *SyncAuthConfigRequestHeader) SetAuthUser(v string) *SyncAuthConfigRequestHeader {
  s.AuthUser = &v
  return s
}

type SyncAuthConfigResponseHeader struct {
}

func (s SyncAuthConfigResponseHeader) String() string {
  return tea.Prettify(s)
}

func (s SyncAuthConfigResponseHeader) GoString() string {
  return s.String()
}




type DeleteuserRequest struct {
  // {'en':'username
  // This parameter must be specified.', 'zh_CN':'用户名
  // 该参数必须指定。'}
  Username *string `json:"username,omitempty" xml:"username,omitempty" require:"true"`
}

func (s DeleteuserRequest) String() string {
  return tea.Prettify(s)
}

func (s DeleteuserRequest) GoString() string {
  return s.String()
}

func (s *DeleteuserRequest) SetUsername(v string) *DeleteuserRequest {
  s.Username = &v
  return s
}

type DeleteuserResponse struct {
  // {'en':'Interface error code, 0-fail,1-success', 'zh_CN':'接口错误码，0-代表失败，1-代表成功'}
  ReturnCode *string `json:"returnCode,omitempty" xml:"returnCode,omitempty" require:"true"`
  // {'en':'Error message', 'zh_CN':'错误信息'}
  ReturnMsg *string `json:"returnMsg,omitempty" xml:"returnMsg,omitempty" require:"true"`
}

func (s DeleteuserResponse) String() string {
  return tea.Prettify(s)
}

func (s DeleteuserResponse) GoString() string {
  return s.String()
}

func (s *DeleteuserResponse) SetReturnCode(v string) *DeleteuserResponse {
  s.ReturnCode = &v
  return s
}

func (s *DeleteuserResponse) SetReturnMsg(v string) *DeleteuserResponse {
  s.ReturnMsg = &v
  return s
}

type DeleteuserPaths struct {
}

func (s DeleteuserPaths) String() string {
  return tea.Prettify(s)
}

func (s DeleteuserPaths) GoString() string {
  return s.String()
}

type DeleteuserParameters struct {
}

func (s DeleteuserParameters) String() string {
  return tea.Prettify(s)
}

func (s DeleteuserParameters) GoString() string {
  return s.String()
}

type DeleteuserRequestHeader struct {
}

func (s DeleteuserRequestHeader) String() string {
  return tea.Prettify(s)
}

func (s DeleteuserRequestHeader) GoString() string {
  return s.String()
}

type DeleteuserResponseHeader struct {
}

func (s DeleteuserResponseHeader) String() string {
  return tea.Prettify(s)
}

func (s DeleteuserResponseHeader) GoString() string {
  return s.String()
}




type ListGroupsRequest struct {
  // {"en":"You can choose between parentGroupId and parentGroupName. It is recommended to pass parentGroupId first to ensure uniqueness.","zh_CN":"parentGroupId和parentGroupName二选一，推荐优先传递parentGroupId，以确保唯一性"}
  ParentGroupId *string `json:"parentGroupId,omitempty" xml:"parentGroupId,omitempty"`
}

func (s ListGroupsRequest) String() string {
  return tea.Prettify(s)
}

func (s ListGroupsRequest) GoString() string {
  return s.String()
}

func (s *ListGroupsRequest) SetParentGroupId(v string) *ListGroupsRequest {
  s.ParentGroupId = &v
  return s
}

type ListGroupsRequestHeader struct {
}

func (s ListGroupsRequestHeader) String() string {
  return tea.Prettify(s)
}

func (s ListGroupsRequestHeader) GoString() string {
  return s.String()
}

type ListGroupsPaths struct {
}

func (s ListGroupsPaths) String() string {
  return tea.Prettify(s)
}

func (s ListGroupsPaths) GoString() string {
  return s.String()
}

type ListGroupsParameters struct {
  // {"en":"Query all user groups under the specified parent group.\nIf the value is null, query all groups under the root directory group.","zh_CN":"查询指定父组下的所有用户组\n不填写时，查全部"}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty"`
}

func (s ListGroupsParameters) String() string {
  return tea.Prettify(s)
}

func (s ListGroupsParameters) GoString() string {
  return s.String()
}

func (s *ListGroupsParameters) SetGroupName(v string) *ListGroupsParameters {
  s.GroupName = &v
  return s
}

type ListGroupsResponse struct {
  // {"en":"Interface error code, 0-fail,1-success","zh_CN":"接口错误码，0-代表失败，1-代表成功"}
  ReturnCode *string `json:"returnCode,omitempty" xml:"returnCode,omitempty" require:"true"`
  // {"en":"Error message","zh_CN":"错误信息"}
  ReturnMsg *string `json:"returnMsg,omitempty" xml:"returnMsg,omitempty" require:"true"`
  // {"en":"content","zh_CN":"数据，下面全是数据的内容"}
  Content *ListGroupsResponseContent `json:"content,omitempty" xml:"content,omitempty" require:"true" type:"Struct"`
}

func (s ListGroupsResponse) String() string {
  return tea.Prettify(s)
}

func (s ListGroupsResponse) GoString() string {
  return s.String()
}

func (s *ListGroupsResponse) SetReturnCode(v string) *ListGroupsResponse {
  s.ReturnCode = &v
  return s
}

func (s *ListGroupsResponse) SetReturnMsg(v string) *ListGroupsResponse {
  s.ReturnMsg = &v
  return s
}

func (s *ListGroupsResponse) SetContent(v *ListGroupsResponseContent) *ListGroupsResponse {
  s.Content = v
  return s
}

type ListGroupsResponseContent struct {
  // {"en":"groupList","zh_CN":"group集合，下面为字段"}
  GroupList []*ListGroupsResponseContentGroupList `json:"groupList,omitempty" xml:"groupList,omitempty" require:"true" type:"Repeated"`
}

func (s ListGroupsResponseContent) String() string {
  return tea.Prettify(s)
}

func (s ListGroupsResponseContent) GoString() string {
  return s.String()
}

func (s *ListGroupsResponseContent) SetGroupList(v []*ListGroupsResponseContentGroupList) *ListGroupsResponseContent {
  s.GroupList = v
  return s
}

type ListGroupsResponseContentGroupList struct     {
  // {"en":"groupName","zh_CN":"用户组名称"}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty" require:"true"`
  // {"en":"groupId","zh_CN":"用户组ID"}
  GroupId *int64 `json:"groupId,omitempty" xml:"groupId,omitempty" require:"true"`
  // {"en":"parentGroupName","zh_CN":"父组名称"}
  ParentGroupName *string `json:"parentGroupName,omitempty" xml:"parentGroupName,omitempty" require:"true"`
  // {"en":"parentGroupID","zh_CN":"父组ID"}
  ParentGroupId *string `json:"parentGroupId,omitempty" xml:"parentGroupId,omitempty" require:"true"`
  // {"en":"authConfigName","zh_CN":"所属组织架构名称"}
  AuthConfigName *string `json:"authConfigName,omitempty" xml:"authConfigName,omitempty" require:"true"`
  // {"en":"remark","zh_CN":"备注"}
  Remark *string `json:"remark,omitempty" xml:"remark,omitempty" require:"true"`
  // {"en":"createTime","zh_CN":"创建时间"}
  CreateTime *int64 `json:"createTime,omitempty" xml:"createTime,omitempty" require:"true"`
  // {"en":"updateTime","zh_CN":"更新时间"}
  UpdateTime *int64 `json:"updateTime,omitempty" xml:"updateTime,omitempty" require:"true"`
}

func (s ListGroupsResponseContentGroupList) String() string {
  return tea.Prettify(s)
}

func (s ListGroupsResponseContentGroupList) GoString() string {
  return s.String()
}

func (s *ListGroupsResponseContentGroupList) SetGroupName(v string) *ListGroupsResponseContentGroupList {
  s.GroupName = &v
  return s
}

func (s *ListGroupsResponseContentGroupList) SetGroupId(v int64) *ListGroupsResponseContentGroupList {
  s.GroupId = &v
  return s
}

func (s *ListGroupsResponseContentGroupList) SetParentGroupName(v string) *ListGroupsResponseContentGroupList {
  s.ParentGroupName = &v
  return s
}

func (s *ListGroupsResponseContentGroupList) SetParentGroupId(v string) *ListGroupsResponseContentGroupList {
  s.ParentGroupId = &v
  return s
}

func (s *ListGroupsResponseContentGroupList) SetAuthConfigName(v string) *ListGroupsResponseContentGroupList {
  s.AuthConfigName = &v
  return s
}

func (s *ListGroupsResponseContentGroupList) SetRemark(v string) *ListGroupsResponseContentGroupList {
  s.Remark = &v
  return s
}

func (s *ListGroupsResponseContentGroupList) SetCreateTime(v int64) *ListGroupsResponseContentGroupList {
  s.CreateTime = &v
  return s
}

func (s *ListGroupsResponseContentGroupList) SetUpdateTime(v int64) *ListGroupsResponseContentGroupList {
  s.UpdateTime = &v
  return s
}

type ListGroupsResponseHeader struct {
}

func (s ListGroupsResponseHeader) String() string {
  return tea.Prettify(s)
}

func (s ListGroupsResponseHeader) GoString() string {
  return s.String()
}




type ListUsersRequest struct {
  // {"en":"You can choose between parentGroupId and parentGroupName. It is recommended to pass parentGroupId first to ensure uniqueness.","zh_CN":"parentGroupId和parentGroupName二选一，推荐优先传递parentGroupId，以确保唯一性"}
  ParentGroupId *string `json:"parentGroupId,omitempty" xml:"parentGroupId,omitempty"`
}

func (s ListUsersRequest) String() string {
  return tea.Prettify(s)
}

func (s ListUsersRequest) GoString() string {
  return s.String()
}

func (s *ListUsersRequest) SetParentGroupId(v string) *ListUsersRequest {
  s.ParentGroupId = &v
  return s
}

type ListUsersRequestHeader struct {
}

func (s ListUsersRequestHeader) String() string {
  return tea.Prettify(s)
}

func (s ListUsersRequestHeader) GoString() string {
  return s.String()
}

type ListUsersPaths struct {
}

func (s ListUsersPaths) String() string {
  return tea.Prettify(s)
}

func (s ListUsersPaths) GoString() string {
  return s.String()
}

type ListUsersParameters struct {
  // {"en":"Query all users under the specified parent group\nIf the value is null, query all users under the root directory group.","zh_CN":"查询指定父组下的所有用户\n不填写时，查全部"}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty" require:"true"`
  // {"en":"Page number of users list\nStart value: 1\nDefault value: 1","zh_CN":"用户列表的页码\n起始值：1\n默认值：1"}
  PageNo *int `json:"pageNo,omitempty" xml:"pageNo,omitempty"`
  // {"en":"The number of rows per page set during pagination query. Value range: 1~50\nDefault value: 20","zh_CN":"分页查询时设置的每页行数。取值范围：1~50\n默认值：20"}
  PageSize *int `json:"pageSize,omitempty" xml:"pageSize,omitempty"`
}

func (s ListUsersParameters) String() string {
  return tea.Prettify(s)
}

func (s ListUsersParameters) GoString() string {
  return s.String()
}

func (s *ListUsersParameters) SetGroupName(v string) *ListUsersParameters {
  s.GroupName = &v
  return s
}

func (s *ListUsersParameters) SetPageNo(v int) *ListUsersParameters {
  s.PageNo = &v
  return s
}

func (s *ListUsersParameters) SetPageSize(v int) *ListUsersParameters {
  s.PageSize = &v
  return s
}

type ListUsersResponse struct {
  // {"en":"Interface error code, 0-fail,1-success","zh_CN":"接口错误码，0-代表失败，1-代表成功"}
  ReturnCode *string `json:"returnCode,omitempty" xml:"returnCode,omitempty" require:"true"`
  // {"en":"Error message","zh_CN":"错误信息"}
  ReturnMsg *string `json:"returnMsg,omitempty" xml:"returnMsg,omitempty" require:"true"`
  // {"en":"content","zh_CN":"数据，下面全是数据的内容"}
  Content *ListUsersResponseContent `json:"content,omitempty" xml:"content,omitempty" require:"true" type:"Struct"`
}

func (s ListUsersResponse) String() string {
  return tea.Prettify(s)
}

func (s ListUsersResponse) GoString() string {
  return s.String()
}

func (s *ListUsersResponse) SetReturnCode(v string) *ListUsersResponse {
  s.ReturnCode = &v
  return s
}

func (s *ListUsersResponse) SetReturnMsg(v string) *ListUsersResponse {
  s.ReturnMsg = &v
  return s
}

func (s *ListUsersResponse) SetContent(v *ListUsersResponseContent) *ListUsersResponse {
  s.Content = v
  return s
}

type ListUsersResponseContent struct {
  // {"en":"pageSize","zh_CN":"输入时设置的每页行数"}
  PageSize *int `json:"pageSize,omitempty" xml:"pageSize,omitempty" require:"true"`
  // {"en":"pageNo","zh_CN":"用户列表的页码"}
  PageNo *int `json:"pageNo,omitempty" xml:"pageNo,omitempty" require:"true"`
  // {"en":"totalCount","zh_CN":"实例总数"}
  TotalCount *int `json:"totalCount,omitempty" xml:"totalCount,omitempty" require:"true"`
  // {"en":"result","zh_CN":"分页结果数据，下面为数据格式"}
  Result *ListUsersResponseContentResult `json:"result,omitempty" xml:"result,omitempty" require:"true" type:"Struct"`
}

func (s ListUsersResponseContent) String() string {
  return tea.Prettify(s)
}

func (s ListUsersResponseContent) GoString() string {
  return s.String()
}

func (s *ListUsersResponseContent) SetPageSize(v int) *ListUsersResponseContent {
  s.PageSize = &v
  return s
}

func (s *ListUsersResponseContent) SetPageNo(v int) *ListUsersResponseContent {
  s.PageNo = &v
  return s
}

func (s *ListUsersResponseContent) SetTotalCount(v int) *ListUsersResponseContent {
  s.TotalCount = &v
  return s
}

func (s *ListUsersResponseContent) SetResult(v *ListUsersResponseContentResult) *ListUsersResponseContent {
  s.Result = v
  return s
}

type ListUsersResponseContentResult struct {
  // {"en":"username","zh_CN":"用户名称"}
  Username *string `json:"username,omitempty" xml:"username,omitempty" require:"true"`
  // {"en":"id","zh_CN":"用户id"}
  Id *int64 `json:"id,omitempty" xml:"id,omitempty" require:"true"`
  // {"en":"email","zh_CN":"邮箱"}
  Email *string `json:"email,omitempty" xml:"email,omitempty" require:"true"`
  // {"en":"areaCode","zh_CN":"区号"}
  AreaCode *string `json:"areaCode,omitempty" xml:"areaCode,omitempty" require:"true"`
  // {"en":"cellphone","zh_CN":"手机号"}
  Cellphone *string `json:"cellphone,omitempty" xml:"cellphone,omitempty" require:"true"`
  // {"en":"groupID","zh_CN":"父组ID"}
  GroupId *int64 `json:"groupId,omitempty" xml:"groupId,omitempty" require:"true"`
  // {"en":"groupName","zh_CN":"父组名称"}
  GroupName *string `json:"groupName,omitempty" xml:"groupName,omitempty" require:"true"`
  // {"en":"bandwidth","zh_CN":"带宽"}
  Bandwidth *string `json:"bandwidth,omitempty" xml:"bandwidth,omitempty" require:"true"`
  // {"en":"remark","zh_CN":"备注"}
  Remark *string `json:"remark,omitempty" xml:"remark,omitempty" require:"true"`
  // {"en":"expireTime","zh_CN":"过期时间戳，0-永不过期"}
  ExpireTime *int64 `json:"expireTime,omitempty" xml:"expireTime,omitempty" require:"true"`
  // {"en":"enableStatus","zh_CN":"启用状态,-1：禁用，0：启用但离线，2：启用且在线"}
  EnableStatus *int `json:"enableStatus,omitempty" xml:"enableStatus,omitempty" require:"true"`
  // {"en":"smsAuth","zh_CN":"短信认证启用"}
  SmsAuth *int `json:"smsAuth,omitempty" xml:"smsAuth,omitempty" require:"true"`
  // {"en":"totpAuth","zh_CN":"totp认证启用"}
  TotpAuth *int `json:"totpAuth,omitempty" xml:"totpAuth,omitempty" require:"true"`
  // {"en":"virtual ip","zh_CN":"虚拟ip"}
  Vip *string `json:"vip,omitempty" xml:"vip,omitempty" require:"true"`
  // {"en":"createTime","zh_CN":"创建时间戳"}
  CreateTime *int64 `json:"createTime,omitempty" xml:"createTime,omitempty" require:"true"`
}

func (s ListUsersResponseContentResult) String() string {
  return tea.Prettify(s)
}

func (s ListUsersResponseContentResult) GoString() string {
  return s.String()
}

func (s *ListUsersResponseContentResult) SetUsername(v string) *ListUsersResponseContentResult {
  s.Username = &v
  return s
}

func (s *ListUsersResponseContentResult) SetId(v int64) *ListUsersResponseContentResult {
  s.Id = &v
  return s
}

func (s *ListUsersResponseContentResult) SetEmail(v string) *ListUsersResponseContentResult {
  s.Email = &v
  return s
}

func (s *ListUsersResponseContentResult) SetAreaCode(v string) *ListUsersResponseContentResult {
  s.AreaCode = &v
  return s
}

func (s *ListUsersResponseContentResult) SetCellphone(v string) *ListUsersResponseContentResult {
  s.Cellphone = &v
  return s
}

func (s *ListUsersResponseContentResult) SetGroupId(v int64) *ListUsersResponseContentResult {
  s.GroupId = &v
  return s
}

func (s *ListUsersResponseContentResult) SetGroupName(v string) *ListUsersResponseContentResult {
  s.GroupName = &v
  return s
}

func (s *ListUsersResponseContentResult) SetBandwidth(v string) *ListUsersResponseContentResult {
  s.Bandwidth = &v
  return s
}

func (s *ListUsersResponseContentResult) SetRemark(v string) *ListUsersResponseContentResult {
  s.Remark = &v
  return s
}

func (s *ListUsersResponseContentResult) SetExpireTime(v int64) *ListUsersResponseContentResult {
  s.ExpireTime = &v
  return s
}

func (s *ListUsersResponseContentResult) SetEnableStatus(v int) *ListUsersResponseContentResult {
  s.EnableStatus = &v
  return s
}

func (s *ListUsersResponseContentResult) SetSmsAuth(v int) *ListUsersResponseContentResult {
  s.SmsAuth = &v
  return s
}

func (s *ListUsersResponseContentResult) SetTotpAuth(v int) *ListUsersResponseContentResult {
  s.TotpAuth = &v
  return s
}

func (s *ListUsersResponseContentResult) SetVip(v string) *ListUsersResponseContentResult {
  s.Vip = &v
  return s
}

func (s *ListUsersResponseContentResult) SetCreateTime(v int64) *ListUsersResponseContentResult {
  s.CreateTime = &v
  return s
}

type ListUsersResponseHeader struct {
}

func (s ListUsersResponseHeader) String() string {
  return tea.Prettify(s)
}

func (s ListUsersResponseHeader) GoString() string {
  return s.String()
}




